### ISSUE TITLE
FireBird (2.5 3.0 and 4.0)  / Interbase support

### ISSUE THREAD

**Issue by fduenas** [HeidiSQL/HeidiSQL#1169]
**Is your feature request related to a problem? Please describe.**
One of the pending databases that are also used is Interbase/FireBird (Local, TCP/IP and embedded)

**Describe the solution you'd like**
For next Major Versions consider to add Interbase/FireBird Soport (Local, TCP/IP and embedded)

**Describe alternatives you've considered**
You can Check IBExpert fro more inspiration

**Additional context**
FireDAC, ZeosLIB, UIB, IBOjects Sopports Interbase/FireBird

https://www.firebirdsql.org/en/documentation/

**Comment by fperana** [comment]
If you need help in beta testing Firebird support, I use it quite extensively in my projects.

**Comment by murilofurquim** [comment]
I can help testing too. I can help fix bugs too, but only if it's possible to develop on Delphi 10.1.

**Comment by asine** [comment]
how about this plan?

**Comment by cartonjeston** [comment]
Just tell you that you do a great job. The day I also work with Firebird, it will work with all the most popular databases and I think it will become the standard database manager, not only for programmers but for use in education. Don't feel the pressure, it's just the uncontrolled desire of firebird fans ...

We all know that keeping software updated from so many different bases is very complicated, a lot of work and time ...
;-)

**Comment by ansgarbecker** [comment]
Just wanted to let you know I started working on Interbase support:
![grafik](https://user-images.githubusercontent.com/7986591/123517634-6c99d900-d6a2-11eb-8341-a3f1d7eaa6f0.png)

If someone knows some SQL queries for getting columns from a table, or any other meta data out of a database, please shout. Many things are obviously available through Delphi's `TFDConnection`, but it would be nice if I had some SQL replacements for at least some of them.

**Comment by murilofurquim** [comment]
Good news!
For metadata I always refer to this article https://www.alberton.info/firebird_sql_meta_info.html.

**Comment by cartonjeston** [comment]
I don't know if it will help, but I do get a link to this thread, to more experienced firebird programmers in case they can help to finish. I recommend anyone reading to do the same ;-)

**Comment by fperana** [comment]
Great news!

Please keep it compatible with Firebird also, they're similar but not
identical, especially regarding new features (functions,
system/monitoring tables, data types...).

About your question, I'd suggest to try installing Flamerobin (a tool
similar to HeidiSQL specific for Firebird), configure a connection to a
DB and watch at system tables (and all the other things you'd like to
explore). Tables' and fields' names are quite self-explaining.

Thanks a lot for your work :)

STUDIO CENTRO SRL - Soluzioni e Servizi - www.studiocentro.it
Sede: 36100 Vicenza - Via Luigi Boccherini, 13 Tel. 0444.56.31.66 Fax
0444.96.43.65 email: ***@***.***
Certificazione ISO/IEC 27001:2013 del 27/12/2018 N°.
280175-2018-AIS-ITA-ACCREDIA

>>> Ansgar Becker ***@***.***> 26/06/2021 17.20 >>>

Questa è la prima volta che ricevi un'email da questo mittente.
Assicurati che sia qualcuno di cui ti fidi. 
Just wanted to let you know I started working on Interbase support:
If someone knows some SQL queries for getting columns from a table, or
any other meta data out of a database, please shout. Many things are
obviously available through Delphi's TFDConnection, but it would be nice
if I had some SQL replacements for at least some of them.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
(
https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FHeidiSQL%2FHeidiSQL%2Fissues%2F1169%23issuecomment-869017474&e=fada5ddf&h=efc9fd09&f=n&p=y)
, or unsubscribe
(
https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFZRHZK5YF7TLZP2CTOV47DTUXV2NANCNFSM4RYIE42Q&e=fada5ddf&h=d2e5e00b&f=n&p=y)
.

-- 
Questo messaggio è stato analizzato con Libraesva ESG ed è risultato
non infetto.
Segnala come spam.
( https://esva.advcloud.it:4443/action/0F36F4056E.A6562/learn-spam) 
Mettilo in blacklist
( https://esva.advcloud.it:4443/action/0F36F4056E.A6562/blacklist)

**Comment by ansgarbecker** [comment]
I have a state in the nightly builds which somehow works moreorless for executing queries and selecting a table:

![grafik](https://user-images.githubusercontent.com/7986591/140027415-110221bd-51e7-4b9f-b30f-e18fd6efe986.png)

But I need some sample database, so I can test more column types, for mapping with Heidi's internal types. Does anybody know of a good demo sql file for Interbase? IBexpert says it has one, but I can't find one in the personal edition I downloaded.

**Comment by realcolaflasche** [comment]
Hi Ansgar,

der Firebird liefert eine Beispiel-DB mit. Ich habe Dir diese mal aus dem
firebird 3 angehangen.
Gegen welche Datenbank testest Du denn? Firebird oder Interbase und gegen
welche Version?

Mit freundlichen Grüßen

Jan Kohlmeyer

Dammweg 8
56295 Kerben
0170/3865184


Am Mi., 3. Nov. 2021 um 09:17 Uhr schrieb Ansgar Becker <
***@***.***>:

**Comment by astek-dsv** [comment]
Congratulations on developing the Firebird database connection. For sure our company will be another new user.

**Comment by ansgarbecker** [comment]
@astek-dsv I planned to have experimental FB/IB support in the next release, which should be ready in one or two months.

I'm just scratching my head why the `TFDConnection` driver wants a `Database` parameter with a local file path even when `Protocol` is set to `ipTCPIP`. In my understanding a TCP/IP connection retrieves the database over the network, not via local files. Can anyone shed some light here?

**Comment by as-it** [comment]
I think that it is because you can have more than one DB on one PC/Server and each DB is just different .FDB file:
![image](https://user-images.githubusercontent.com/23263469/155944407-da1ccb97-6bd8-4c4e-8aa5-02629f6b83da.png)

**Comment by murilofurquim** [comment]
> @astek-dsv I planned to have experimental FB/IB support in the next release, which should be ready in one or two months.
> 
> I'm just scratching my head why the `TFDConnection` driver wants a `Database` parameter with a local file path even when `Protocol` is set to `ipTCPIP`. In my understanding a TCP/IP connection retrieves the database over the network, not via local files. Can anyone shed some light here?

This behavior is correct. Firebird doesn't manage databases in a single folder like other DBMS, that can be referred only by their name, FDB files can be anywhere on the server, so even on a remote connection you need to specify the full local path for the database file, along with the host. This connection can be simplified by configuring an alias for the database path in the file "aliases.conf" or "databases.conf". But the full path connection should be supported.

**Comment by realcolaflasche** [comment]
Shoud I post issues to Firebird hiere or shoud I do a new ticket?
For example in TInterbaseConnection.GetTableColumns you get the collection this way:
`    ' LEFT JOIN RDB$COLLATIONS coll ON f.RDB$COLLATION_ID = coll.RDB$COLLATION_ID'+
    ' LEFT JOIN RDB$CHARACTER_SETS cset ON f.RDB$CHARACTER_SET_ID = cset.RDB$CHARACTER_SET_ID'+`

better is this way:

`    ' LEFT JOIN RDB$CHARACTER_SETS cset ON f.RDB$CHARACTER_SET_ID = cset.RDB$CHARACTER_SET_ID'+
    ' LEFT JOIN RDB$COLLATIONS coll ON f.RDB$COLLATION_ID = coll.RDB$COLLATION_ID'+
    '                              AND F.RDB$CHARACTER_SET_ID = COLL.RDB$CHARACTER_SET_ID'+`

otherwise you can have each column multiple times

**Comment by realcolaflasche** [comment]
Hi, I want to do a pull-request. I did the following things:
- added FireDAC.Phys.FB to use Firebird
- select for spCurrentUserHost for Firebird
- edited GetTableColumns for firebird
- Implemented GetTableForeignKeys for firebird
- FetchDbObjects for Firebird:
  - new select for Tables and views
  - procedures
  - Triggers
  - Functions

but I alwasy get "access denied". Do I something wrong or do I have to apply so that I can change something

**Comment by realcolaflasche** [comment]
Yes, any client application need these. Is it neccesary do deliver these files? And you deliver them in a specific version. If someone needs another version, he has to change it anyway.

My suggestion would be to do Firebird as Networktype so you have the types:
Interbase (Local | TCP/IP)
Firebird (Local | TCP/IP)
And for the library the user can specify his own client-Library-file. 

For that, you have to create a TFDPhysIBDriverLink or TFDPhysFBDriverLink and set the VendorLib and the Property DriverId and set in the TFDConnection the DriverName to the DriverId.

**Comment by ansgarbecker** [comment]
Makes sense, now that I read about this virtual driver id. Just did that, so now we have 4 instead of 2 network types:
![grafik](https://user-images.githubusercontent.com/7986591/157523531-0f517c45-3930-47cf-9c0e-7d9d7504112d.png)

Use the latest nightly installer + update to the latest build to get the dlls into the library pulldown.

**Comment by ansgarbecker** [comment]
Closing this  for now. Please further issues in separate tickets.
