### ISSUE TITLE
whacky column auto-sizing in table editor

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#1188]
**Describe the bug**

table editor now seems to have some interesting opinions on how to autosize the columns, which makes them huge, and others are scrolled off the screen.

**To Reproduce**
1. Go to any table editor
2. Gaze upon the huge columns

**Expected behavior**

columns are auto-sized to contents.

**Screenshots**

![column-autosize](https://user-images.githubusercontent.com/43234/96026639-60276600-0e1c-11eb-8d12-c76fd519c178.png)

**Environment:**
 - OS: Win10
 - HeidiSQL: 6099
 - Database type and version Percona/MySQL 5.6.21

**Comment by ansgarbecker** [comment]
Your screen tells me you have activated high-dpi support for your HeidiSQL icon. This is unsupported, due to exactly such issues - there are many of these wrong column width bugs then. Please turn off high-dpi support in your HeidiSQL shortcut, or set it to "Application":

![grafik](https://user-images.githubusercontent.com/7986591/96027298-f927a280-0e57-11eb-84b9-b0ebaca32663.png)

**Comment by leeoniya** [comment]
yep, that was it. thanks!
