### ISSUE TITLE
Bit default value

### ISSUE THREAD

**Issue by Skymidt** [HeidiSQL/HeidiSQL#1192]
Can't put a default value on bit field.

**Comment by Skymidt** [comment]
MariaDB - 10.4.10
HeidiSql - 10.0.0.6104

**Comment by rentalhost** [comment]
Please, fill the template:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment:**
 - OS: [e.g. Windows 10, Ubuntu/Wine5.0]
 - HeidiSQL version [e.g. 11.0.0.6050]
 - Database type and version [e.g. MariaDB 10.3.12]
```

**Comment by grooverdan** [comment]
This might be the same as https://jira.mariadb.org/browse/MDEV-13244
https://www.heidisql.com/forum.php?t=24014

**Comment by ansgarbecker** [comment]
I don't guess so, as that MariaDB report is about numeric columns, not BIT columns.
Anyway, this report is invalid, due to the missing description.

**Comment by grooverdan** [comment]
The MariaDB numeric column defaults are no-longer quoted, and yes, bit columns defaults have a `b'0'` syntax which is different too and also comes down to the `show create table` format.

[dbfiddle](https://dbfiddle.uk/?rdbms=mariadb_10.4&fiddle=2a04cdbf9bbf8213027c65ba831975fe)

But quite right, as a bug report, this needs a description rather than both of us guessing :-)
