### ISSUE TITLE
Alt being pressed when using F10

### ISSUE THREAD

**Issue by MaryBonney** [HeidiSQL/HeidiSQL#1214]
I have noticed an odd thing with the latest version of HeidiSQL (both portable and installed).

I am used to using F9 to reformat and F10 to run a script. If I change the shortcuts so that this is the setup, I find that pressing F10 makes the File menu highlighted as would normally happen when Alt is pressed. If I press another key after that, it is like selecting something from the File menu. I have to press F10 twice to cancel the highlight.

Having got used over the years to using these keys, I would prefer not to change them. What does F10 do in the default setup and can this ALT selection be avoided?

I have reverted to version 11.0.0.5919 at the moment which does not have this problem.

**Comment by ansgarbecker** [comment]
Please use the issue template.

I can reproduce that here, but I have no clue how to change that menu hightlighting by F10.

I suppose this must be caused by a change in the underlying VCL library in the updated Delphi version. I did not change that explicitely in HeidiSQL.

Now that I press F10 in Firefox, Thunderbird and Notepad++, I notice the same behaviour as in HeidiSQL. So this looks more like a bugfix, rather than a bug.

I can just recommend to use the default keys, or at least not F10.
