### ISSUE TITLE
Windows 10 close the program by click on top right corner 'Х'

### ISSUE THREAD

**Issue by Lunatig** [HeidiSQL/HeidiSQL#1217]
**Describe the bug**
When you close the program left click on the upper right corner where the cross closes the window behind HeidiSQL. 

**To Reproduce**
1. Open window HeidiSQL
2. Click on top right corner 'X'. Upper right corner tip of the monitor
3. The HeidiSQL window will still be open. But the window behind the HeidiSQL window will be closed
4. Get angry and spit at the monitor

**Expected behavior**
Сlosing the HeidiSQL program window

**Environment:**
 - OS: [e.g. Windows 10]
 - HeidiSQL version [e.g.  11.1 ( 11.0.0.6101)]

**Comment by WesleyM77** [comment]
I ran into this issue a few times before as well, never noticed it was Heidi. I think the issue stems from the fact that the 'X' button doesn't fully extend to the top and right of the screen and leaves a few pixels for clicking through, though I wasn't able to recreate it just now.

**Comment by Lunatig** [comment]
Yes. it's like a couple of pixels are missing. but the standard full-screen window extension doesn't help. and this situation is only with heidi

**Comment by ansgarbecker** [comment]
Is that happening with a custom theme, or also with the default "Windows" theme?

**Comment by WesleyM77** [comment]
I'm using the Material Dark theme option given during installation.

**Comment by Lunatig** [comment]
The same on all themes.

**Comment by ansgarbecker** [comment]
@Lunatig I meant the theme in HeidiSQL. See Tools > Preferences > General > "Style Theme". I cannot reproduce that with the Windows theme here, which is why I was asking.

**Comment by ansgarbecker** [comment]
I installed the latest Delphi 10.4.1 update, but this issue is still present with it, when a style/theme is selected. Not with the "Windows" style, once again.

I also searched https://quality.embarcadero.com/ for relevant issue reports, without luck.

Now that I have a closer look at the themes, I see it's just the Material theme having this issue. For example the "Windows 10 Dark" does not have it. On the other hand, with "Carbon" it is even worse.

As the Material theme is maintained by @CharlieEtienne , this should be reported to https://github.com/CharlieEtienne/material-vcl/issues

**Comment by ansgarbecker** [comment]
@Lunatig please report to https://github.com/CharlieEtienne/material-vcl/issues

**Comment by CharlieEtienne** [comment]
Hi @ansgarbecker, hope you're ok.

I was on other projets and I didn't use HeidiSQL in the entire year. It might be complicated for me to keep maintaining this theme. Would be nice if someone could help me to maintain it. If someone is interested, feel free to contact me in https://github.com/CharlieEtienne/material-vcl/issues !
