### ISSUE TITLE
Problem importing CSV

### ISSUE THREAD

**Issue by alansystem** [HeidiSQL/HeidiSQL#1258]
Hello, I'm from Brazil, sorry for my bad English.

First, thanks for developing such useful software for our day to day, I found a bug in the software, follow the image:

![image](https://user-images.githubusercontent.com/308702/102003285-0f30d280-3ce4-11eb-85d0-ceaf56b89f2b.png)

**Comment by ansgarbecker** [comment]
> ... sorry for my bad English.

That's not a problem - seems good enough.
Please use one of the issue templates the next time:
![grafik](https://user-images.githubusercontent.com/7986591/102012026-58b30900-3d48-11eb-8214-d2481c199854.png)

These overlapping buttons should be fixed in the next build.

**Comment by alansystem** [comment]
I can't select the columns, because other functionality is overlapping, doesn't that seem like a problem?

**Comment by ansgarbecker** [comment]
Yes, that's why I pushed some changes and said this may fix the issue.
Problem is a longer translation for the words "up" and "down" on these buttons, which had `AutoSize` enabled. I changed that, the new build is compiled and you could update to the latest build now to retry. (Help > Check for updates)

**Comment by alansystem** [comment]
Thank you very much, I did the update and solved the problem:

![image](https://user-images.githubusercontent.com/308702/102082554-ec401480-3df0-11eb-8e7f-8f8cf2a13052.png)
