### ISSUE TITLE
Access Violation on 32bits version (not on 64bits) on mouse hover DBTree

### ISSUE THREAD

**Issue by Delphichem** [HeidiSQL/HeidiSQL#1270]
**Describe the bug**
Moving mouse to dbTree cause an access violation (on 32 bits version).

**To Reproduce**
1. Connect to mysql
2. Try to select a DB or a table.
3. See error

**Environment:**
 - OS: Windows 10,
  - HeidiSQL since version 11.0.0.6190
 - MySQL 5.7 [libmysql-6.1-32.dll]

**Comment by ansgarbecker** [comment]
This crash was obviously caused by my commit 67e3dc0a5181b2d053e15b9ce32822cf7a8a6814 - which did not change anything in the 64 bit version. Thanks for reporting about the difference in 32/64 bit. Should be fixed in the next build - this time I tested the 32bit version as well.

If the 32bit version behaves differently to the 64bit one, I am just thinking I should probably remove the 32bit support in HeidiSQL. But I guess there are still quite a few people using it, not sure.

**Comment by Delphichem** [comment]
Thanks for the fix, but please don't drop the 32 bits version, we still unesing it.

**Comment by ansgarbecker** [comment]
Out of curiosity: You are using the 32bit version on a Win10 installation?

**Comment by Delphichem** [comment]
Yes, some our customers still run on Windows 7 32bits version and MySQL 5.6 and 5.7 versions.

**Comment by ansgarbecker** [comment]
Windows 7 does not get security updates any longer. Your customers should upgrade.
Well, that's a different topic. I only wonder if there are many supported Windows installation in 32bit mode still, or whether these are all old systems. There will definitely be a point where I am going to drop 32bit support for HeidiSQL.

**Comment by Delphichem** [comment]
I understand.
