### ISSUE TITLE
Issues with table names in query result tabs and missing toolbar icons

### ISSUE THREAD

**Issue by mircea-postolache** [HeidiSQL/HeidiSQL#1297]
**Preconditions**

* HeidiSQL version: HeidiSQL 11.1 64_Portable
* Database type and version: MySql (5.7.32-0ubuntu0.18.04.1)
* OS: Ubuntu 18.04.5 LTS (using Wine 3.0)

**Describe the bug**

The new versions of HeidSql Portable (didn't try the Ubuntu packages lately) have some missing icons in the toolbar and a bigger problem with displaying the table name in the query result tab name. I will attach 2 pictures to outline these issues (one from an older version that works properly and another from a newer one)

**To Reproduce**

**Screenshots or Crash reports**

![icons-and-tableName-NO-problems](https://user-images.githubusercontent.com/8749315/106145818-a790f280-617e-11eb-8d12-a3680d6f345f.png)
![icons-and-tableName-problems](https://user-images.githubusercontent.com/8749315/106145821-a8298900-617e-11eb-8926-79f359f51463.png)

**Comment by ansgarbecker** [comment]
These "missing" icons are disabled buttons. Yes, they look different than on Windows 10, but I suppose that's the way Wine does it here. I can't do much here, apart from recommending a newer Wine version.

The tab captions is as far as I see a general issue, and caused by the way how you execute a query batch. Please watch out if you had "Execute batch in one go" activated, like in the following screen, and retry using "Execute queries one by one" instead:

![grafik](https://user-images.githubusercontent.com/7986591/106148782-c50f8d80-6179-11eb-9f51-0dcca8d9669b.png)

And please update to HeidiSQL 11.2

**Comment by mircea-postolache** [comment]
Thank you for the prompt response. I wasn't aware of that setting until now, probably on the older versions the behavior was defaulting to this behavior. Indeed after setting the batch execution setting all the tabs are now named properly. Regarding the icons I will try an upgrade as you suggested but that is not such a big nuisance right now.
Thank you very much for all your work and support.

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
