### ISSUE TITLE
HeidiSQL freezes if it cannot connect to the database

### ISSUE THREAD

**Issue by elieobeid7** [HeidiSQL/HeidiSQL#1306]
I'm on Windows 10, 64 bit latest update, using HeidiSQL latest version (just downloaded it today).

I'm trying to connect to AWS rds database, I must be behind a VPN to do that, if I am, everything is fine. 

If I forget to turn on the VPN and I try to connect, HeidiSQL won't be able to connect to the server and it freezes, nothing works, I have to wait for windows 10 to kill it or kill it myself using the task manager. It would be nice if this scenario could be handled in a better way.

**Comment by ansgarbecker** [comment]
Was there a reason why you deleted the issue template?

Are you sure you gave HeidiSQL 30s or 60s to return with an error?

**Comment by elieobeid7** [comment]
I gave HeidiSQL at the very least 4 minutes and it kept loading and trying to connect, just did that right now before posting this reply.

I deleted the template because all I wanted to do is to write those two sentences and leave,

**Comment by ansgarbecker** [comment]
Assuming your AWS rds is a MySQL database, and further assuming you get some physical connection to it, despite of the missing VPN, you could look up the `connect_timeout` variable (once you have a connection):

    SELECT @@connect_timeout;

But I'm unsure if that's relevant here, and if you hit the host at all due to the missing VPN.

So what I just did was to enably the "Query timeout" setting for MySQL/MariaDB mode:
![grafik](https://user-images.githubusercontent.com/7986591/107158649-dfbce000-698b-11eb-9518-19df526170ee.png)
... and use that setting for the `MYSQL_OPT_CONNECT_TIMEOUT` option.
The next HeidiSQL build has this code, so you should give it a try.

Apart from that I just found the advice to create a VPC security group in AWS, but I know nothing about that, so this might be irrelevant: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.RDSSecurityGroups.html

**Comment by elieobeid7** [comment]
I Will try that, thank you so much
