### ISSUE TITLE
Cannot setting keyboard shortcut  use "ctrl+enter"

### ISSUE THREAD

**Issue by consatan** [HeidiSQL/HeidiSQL#1325]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: Mysql 5.7.33
* OS: Windows 10.0.19042.804

**Describe the bug**

Keyboard shortcut cannot use  `Ctrl+Enter`

**To Reproduce**

1. Go to 'Tools'
2. Click on 'Perferences'
3. Click on 'Shortcuts'
4. Click on 'Data'
5. Click on 'P&ost'
6. Press 'BS' in 'Shortcut'
7. Click on 'SQL'
8. Click on 'Run Seclection'
9. Press 'Ctrl+Enter' in 'Shortcut'

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Confirmed. Shortcut box says Keine/None when pressing <kbd>Ctrl+Enter</kbd>, same with <kbd>Enter</kbd> alone.
Not sure what causes this, have to consult the documentation.
Probably there's a [workaround](http://www.delphigroups.info/2/2a/123704.html).

**Comment by sedurm85** [comment]
I am finding to solved.
first. just install heidsql 10.x  version. this version suppored shourcut + enter key
second. config export (ex, heidsql_config.txt)
third. install hedisql latested version.(ex. 11.2.xx)
fourth. config import (heidsql_config.txt)
fifth. check your shourcut.

Caution. Don't change your shorcut afer fitth step. Because  shorcut(enter key) is reset.

**Comment by Cubittus** [comment]
Just encountered this issue.
The relevant line in the settings file is:
`Shortcut1_actExecuteQuery<|||>3<|||>16397`
If you don't want to install an older version, edit an exported settings file to contain this line, then re-import.
(The value 16397 is hex 0x400d which consists of 0x4000 (scCtrl) plus 0x0d (vkReturn))

**Comment by SilasRodrigues19** [comment]
Hey @consatan 

There is an alternative solution for this using another program.

1. You can download the AutoHotkey program from the following link:
https://autohotkey.com/

2. Create an `.ahk` script with whatever name you prefer.

3. Paste this content inside:

```ahk
#IfWinActive ahk_exe heidisql.exe
^Enter::Send ^{F9}
+^Enter::Send {F9}
#IfWinActive
```

In this case, I set it to `CTRL`  `Shift` `Enter` for the `Run` option, which defaults to `F9`

And I configured `CTRL` `Enter` to execute the `Run Selection` option, which defaults to `CTRL` `F9`

The `IfWinActive` condition checks if the HeidiSQL program is open and remaps the keys only for it, so when executing the script the keys remain normal in other locations and are only remapped within HeidiSQL itself.

**Comment by ansgarbecker** [comment]
I see the shortcut editor works well with <kbd>Ctrl+Enter</kbd>, either since 616c49c2273ec925ccb68791f8e3736df8b23b74 or since the Delphi 11.3 update: b0e2ef27834e20d16d3ecb09e71b56192259b88a, both from previous year.

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/dbe0ff6c-5e57-4cd7-81e1-8aaaed52f118)
