### ISSUE TITLE
Encoding broken or incorrectly detected for "Opening large files" process.

### ISSUE THREAD

**Issue by boneill81** [HeidiSQL/HeidiSQL#1339]
**Preconditions**

* HeidiSQL version: 11.1.0.6116
* Database type and version: MySQL 5.7.24
* OS: Windows 10

**Describe the bug**

- Importing a large SQL file with special characters offers to run the files directly.
- However the encoding is not correctly detected and Irish/special characters are converted to garbage characters.
- When loading an SQL file normally you are offered the option to select encoding.
- The "Opening large files" dialog does not offer this option.
- I have compared against MySQL Workbench and the encoding is correctly determined in Workbench for the same import script.

**To Reproduce**

1. Create a test db and table with a character set of latin1.
2. Load some large SQL file containing special characters.
3. "Opening large files" dialog appears.
4. Choose to run the file directly.
5. Review the table and the special characters will be shown with broken encoding.

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/16405207/111344905-b40cd400-8674-11eb-94b1-916cbef6fbd3.png)

**Comment by ansgarbecker** [comment]
It's not the "opening large files" which does not offer the encoding selection, but the menu or action right before that.
Opening a file through _File > Load SQL file_ offers the encoding in the open-file-dialog:
![grafik](https://user-images.githubusercontent.com/7986591/111353336-7d8b8500-8685-11eb-8838-f58745d7c86d.png)

But I guess you opened it differently?

**Comment by boneill81** [comment]
Ah! sorry I was perhaps doing things too quickly and missed the pre-step. As mentioned in the earlier post, I had seen the option when loading smaller files but when loading a larger file I had missed the option for the encoding. Thanks for the update.

On the topic, a quick question, why would the encoding be incorrectly detected? I tested the same script file in multiple editors Notepad++, GLOGG and also WorkBench and the same issue with encoding was not observed, all showed the characters fine. Just wondering why it would be incorrectly detected so that I know for my own knowledge in future.

Thanks again and sorry for the confusion.

**Comment by ansgarbecker** [comment]
Most incorrect detections are due to a too small chunk of text being analyzed. In cases where you have an utf-8 file, bytes of characters are identically to latin1, as long as there is no critical character (like ä ö ü). So, if the first 1mb of your file anyway contains only latin1 characters, and the application only checks 1mb, the file is detected as latin1. If then the next character is utf-8 char, the detection has done it wrong.
I added a warning dialog in HeidiSQL's open-file-dialog, when you select "Auto-detect", so the user is probably motivated to manually select the right encoding.

My question remains: how did you open that file? Was it that open dialog, and did you just ignore the encoding dropdown?

**Comment by boneill81** [comment]
OK good to know thanks. Yes I opened the file using the same dialog in your screen-shot but missed the encoding option when running with the large script file. Thanks for the help.
