### ISSUE TITLE
Option to export only selected column(s) from result set

### ISSUE THREAD

**Issue by yphastos** [HeidiSQL/HeidiSQL#1360]
**Is your feature request related to a problem? Please describe.**
When looking at results, there is already an option to export the rows as several formats, and he have the option to either export the selected rows, or all rows, as seen here:

![image](https://user-images.githubusercontent.com/13773388/115911586-e3f98500-a433-11eb-9231-c2adbdbd1c83.png)

But there is no option to export data from only certain column(s). e.g. from a result data I may want to just copy the "client_number" or "invoice_number" columns, instead of all of them.

**Describe the solution you'd like**
Add an option in the "Export grid rows" dialog, to be able to only export the selected column(s) data, 
maybe an extra option called "only selected column" and maintain all other options (output format, include column names / auto increment col, etc). So we could even export the column from only selected rows, or all of them.

**Describe alternatives you've considered**
Of course I could edit my query to only get such results, but it would be cumbersome and unnecessary.
Or I could right click on the column headers section and uncheck whichever columns I don't want, one by one, but of course is tremendously time consuming for what should be an easy option.

**Additional context**
You could add the option to the existing "Export grid rows" dialog (and maybe rename it to "Export data"), and give an option to choose only selected columns. The rest of options should be maintained (format options, include column name, separators, etc)

In my particular case, I only need one column at a time, and I see that the result grid doesn't allow to select several columns (as it does for rows), but if possible, it could be nice if we could select several columns at once.

If it's not possible, I'm OK to only have one (current) column exported.

Note that I've seen a similar issue reported, but it is more focused on being able to export a "square selection", which is not necessarily the same.

**Comment by ansgarbecker** [comment]
Issue #35 is similar, but I'm not really clear if that's meant for exporting or for updating.
This forum thread asks for selection of single columns: https://www.heidisql.com/forum.php?t=25202

I just checked possibilities in the underlying VirtualTree, played with its options. For example, currently `toFullRowSelect` is activated. Intuitively I turned it off and expected to be able to select fewer columns, but that's not the case. Also, `toAlwaysHideSelection` does nothing helpful here.

It turns out exporting a column subset would need to be configurable in the export dialog. Probably with such a menu?
![grafik](https://user-images.githubusercontent.com/7986591/149073855-60a0d2a9-229d-4ab8-ba55-3ed1b6db912e.png)

But that looks redundant, as there is also the columns selector above the datagrid:
![grafik](https://user-images.githubusercontent.com/7986591/149074035-58d41254-4722-4516-9f45-04738e18c924.png)

You say it's tremendously time consuming to uncheck unwanted columns there. But I don't see how it can be quicker or easier to do the same in the export dialog.

**Comment by yphastos** [comment]
Hello

The existing column selector you mention only applies (afaik) for TABLE data, and not RESULT data.
And it is indeed useful because it allows to un/check all columns at once:

![image](https://user-images.githubusercontent.com/13773388/149181778-f9fc6c5e-fef9-473c-b7d5-4278b1854c1a.png)

But in the result set, where it can be data from complex queries involving several tables, the difference is that the equivalent option (right clicking on the column headers), does show a column list, but it **doesn't** have a `(un)select ALL` option.

![image](https://user-images.githubusercontent.com/13773388/149181849-ab0d29df-8a23-4f82-9e5d-46f663b3dca6.png)

**It is there where it is cumbersome to uncheck ALL columns if I only want one one or a few.**

It would be enough if it let us un/select all columns as in the other (table data) option.
And the same would apply in the export dialog.

The dropdown menu you show as an example would be perfect, assuming the `All columns` toggles them instead of always selecting them, so we can easily uncheck all first, and then select the only few ones we want.

Being able to quickly un/select all columns would solve the issue in either option (result set and export dialog), or both if you can.

Thanks again.

**Comment by ansgarbecker** [comment]
Next build has a "Toggle" menu item, in the context menu of all grids and lists:

![grafik](https://user-images.githubusercontent.com/7986591/149281387-973ae32a-33dd-4c1b-9c55-c1dc474ae323.png)

Note the last one is always left hidden, so the user does not accidentally remove the header area with the ability to right-click.

**Comment by yphastos** [comment]
Perfect!

It works great for what I needed.

Thank you very much!
