### ISSUE TITLE
No functions/constants in list "default value" and "on update"(MySql 8.0)

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#1543]
**Preconditions**

* HeidiSQL version: 11.3.0.6419
* Database type and version: MySql 8.0 (libmysql.dll)
* OS: Windows 10 (64 Bit)

**Describe the bug**

No functions/constants in lists "default value" and "on update"

**To Reproduce**

**Screenshots or Crash reports**

![изображение](https://user-images.githubusercontent.com/3521094/155427001-42e09c0a-9edd-4086-b555-b35cb3dc9db2.png)

**Comment by ansgarbecker** [comment]
These function names are missing because you don't have the new functions*.ini files I created recently. Please use the latest built installer to get these:

![grafik](https://user-images.githubusercontent.com/7986591/155583757-d2f0964f-da97-4d09-b907-c5b27bc5864c.png)


https://www.heidisql.com/installers/HeidiSQL_11.3.0.6414_Setup.exe

Alternatively, you can download these ini files from the repository and place them into your HeidiSQL directory:
https://github.com/HeidiSQL/HeidiSQL/tree/master/out
