### ISSUE TITLE
Show multiple tables at once (extra 'Data' tabs)

### ISSUE THREAD

**Issue by Mondane** [HeidiSQL/HeidiSQL#155]
## Steps to reproduce this issue

Not implemented yet.

## Current behavior

Not implemented yet.

## Expected behavior

- Connect to a server
- Select a database
- Select a table and optional apply some filters
- ctrl+click another table to open it in a new Data tab

Now, switching between both Data tabs, the data can be easily be compared.

## Possible solution

n/a

## Environment

Ubuntu 16.04

* **HeidiSQL version:** 
9.5.0.5196

**Comment by ansgarbecker** [comment]
I recall there also were people asking for multiple "Table" tabs. The table + data tab are alwas shown at the same time, at least if it's a table or view, not a trigger, procedure or event.

Can you please explain more detailed what you are trying to achieve with multiple data tabs, which is currently not doable? Also, please rethink the whole idea along with the above mentioned table tab.

**Comment by oliveru** [comment]
If I understand correctly, at least, the feature I'd like to see is: 
You filter something in data tab.
Somehow (with a button?) open the result in a query tab, instead of copying the query out of history.
Now you can compare it with another connection e.g.

**Comment by Mondane** [comment]
Well, duplicate tables tabs aren't that necessary. What I would like to achieve is something like this when looking at the same database:

- table orderlines, has a foreign key to products
- table products

Instead of making a query and join the products, which only shows those products joined to the orders, I would like to show both 'data'-tabs next to eachother. Each tab should have the filter functionality.
Now, I can filter both orderlines and products at the same time, which makes understanding the data easier.

Opening an extra dbserver connection would be cool too, but I can manage that by opening another instance of HeidiSQL. Although I have a few friends who don't like that and would be very happy if one HeidiSQL instance could handle several connections at once.

In the above story, the 'table' tab should only show the information for the currently selected table in the sidebar.

**Comment by Mondane** [comment]
@ansgarbecker do you need more information for this request?

**Comment by ansgarbecker** [comment]
> Although I have a few friends who don't like that and would be very happy if one HeidiSQL instance could handle several connections at once.

HeidiSQL can open multiple sessions at one time since the beginning. Just open a second session via session manager. You can even have multiple connections to the same server/session. This is only limited by yourself, when you feel the tree on the left gets to much clutter.

Note that you also can assign a color to a session, in File > Select session background color.

Also, you can have multiple query tabs open at once. This is the way to go currently, when you want to have multiple tabs with the same table data. You just need to write the `SELECT` code manually there.

Please make yourself more familiar with the tab and session features in HeidiSQL. If you still think multiple data tabs have a real use case afterwards, then let's discuss that here.

**Comment by penCsharpener** [comment]
I love the background colour feature. I was thinking about suggesting it but once again it's already there. 

Reading the last comments I think making the query tabs persistant (see #140) solves this issues mostly as well. Rather than having more datatabs you use query tabs as suggested by @ansgarbecker and they aren't lost when closing HeidiSQL. The only things missing then would be the quick filter or the 'select column' menu which are very useful. Could they be added dynamicly for query tabs?

**Comment by cytsunny** [comment]
I understand that HeidiSQL want to be intuitive that the data tab is always the data of the selected table? So, one possible way would be allow select multiple tables on the left side?

I really love HeidiSQL, but this is a feature I really need. I am forced to switch back to MySQL Workbranch for now because it is lacking this feature of viewing multiple table as tabs.

**Comment by ansgarbecker** [comment]
Closing due to solved issue #140 and no further ideas and use cases here.

**Comment by omzy83** [comment]
MySQL Workbench has this feature. I personally find it very useful when looking at data across several tables. I know I can open multiple instances of Heidi but it would be so much simpler if the "Data" tab could be replaced with multiple "Table" tabs.

I understand the interface would need to be changed significantly to accommodate this request but I think it would be a good change. The "Host", "Database" and "Table" tabs are probably not used that often so they should only be shown via a right click option in the sidebar.

**Comment by bjquinn** [comment]
+1, when dealing with multiple tables, it's confusing to have multiple instances of heidisql open, rather than multiple tabs that you can switch back and forth between

**Comment by lubocheng** [comment]
+1,this is a forgotten feature

**Comment by petersteele111** [comment]
+1 for this. Literally just about every other DB software has the ability to open multiple tables at once under different tabs so we don't have to write queries just to view basic data and keep going back into the explorer to open another table we might need to look at. 

Your suggestion of just opening another instance of Heidi seems a bit disingenuous. Imagine in an IDE or VS Code you could only have one tab/file open at a time, asked for the ability to open multiple things at once, and they came back and told you to learn the system better and just open up multiple instances of VS Code or your IDE to see different files. Not cool to even suggest that to be honest. There are a plethora of reasons to need to open multiple tables in different tabs, and just because you can't think of any you feel are valid, is no reason to dismiss the suggestion and a feature that literally just about any other DB management tool offers by default. 

I get its open source and we aren't paying for the software outside of donations, so I'm not going to bitch too much about it, but at the same time, that sort of mentality and dismissal is not cool and really puts a bad taste in the mouth of those that might be newer to open source software and stumbling upon this thread for the first time.

**Comment by omzy** [comment]
Here's a simple solution to the problem. Add a right click option to the table called "New Query" (or something similar, and preferably as the first option), which when clicked will open a new "Query" tab that runs the query:

`SELECT * FROM <databasename.tablename> LIMIT 1000`

Of course we can do this manually at the moment, but something like this will save a huge amount of time when opening multiple tables.

**Comment by ansgarbecker** [comment]
Ok I'll give it a try - thanks to all for ideas.

**Comment by ansgarbecker** [comment]
Issue #604 made it into the last v12.11 release, which is I think quite exactly what @allsorts46 describes above. You can even select multiple tables in the database tab, and let HeidiSQL create one new query tab for selected tables:

![Image](https://github.com/user-attachments/assets/70f57d63-2094-4b79-aa9f-2f71f34a134b)

**Comment by allsorts46** [comment]
> Issue [#604](https://github.com/HeidiSQL/HeidiSQL/issues/604) made it into the last v12.11 release, which is I think quite exactly what [@allsorts46](https://github.com/allsorts46) describes above.

This is definitely a very welcome addition, thank you for that.

What I was proposing goes slightly further though, in that it would also copy the current filtering in the Data tab to the new tab as a query. I believe the 'Select top X rows' option always creates a simple 'select all with limit' query.

You already have a helpful UI in the data tab for showing/hiding columns, adding sort order and filter conditions, effectively a 'query builder'. And the Data tab must already be generating an SQL query which includes all these options, to populate its result grid. It would be great to have a quick option to just take that generated SQL and throw it into a new tab.

Just some suggestions of where such an option could go;

![Image](https://github.com/user-attachments/assets/8ef17a71-29cb-4748-a412-6c707550c872)

1. Tab bar context menu
2. Tab bar next to new tab button (maybe only when Data tab is active?)
3. With the 'Clear data tab filter...' option in the table context menu
4. On the main toolbar near the options to load/save SQL
5. (forgot to label) in the context menu when right-clicking on the results grid.

My personal opinion is that 1 or 2 (most of all 2) make the most contextual sense, but really whatever is easier to implement would still be great.

My hope is that the vast majority of the code needed to implement this already exists (however the Data tab generates its query to populate the results) so that all that is needed is a small UI option to get that same generated SQL and put it in a new tab.

Thanks for considering this, really appreciate the excellent tool you've built.

**Comment by moynulahmed** [comment]
There's a big difference a Data tab and Query Tab.

I am a heavy user of the Data Tab and rarely have to write SQL. 

And yes having the ability to have multiple Data Tabs would make it very convenient. 

On Windows I do open multiple instances at times.  And switch between sessions.  Haven't figured how to run multiple sessions on the Mac.

If it can't be done due to requiring major rework then it's not a problem.. I've managed without this feature for over 8 years.

**Comment by rotsch** [comment]
@ansgarbecker would it be possible to name the query tab according to the table/view name from where it was opened? Having Query, Query `#2`, Query `#3`, etc. doesn't really help with organizing multiple tabs.

**Comment by ansgarbecker** [comment]
@rotsch just did that - sounds reasonable. Note we're talking about the contect menu and the "_Select top x rows_" action in it:

<img width="573" height="221" alt="Image" src="https://github.com/user-attachments/assets/2d09a2a5-38c4-4ac2-ac73-ded66d08e441" />
