### ISSUE TITLE
Unable to download new version as download button is disabled

### ISSUE THREAD

**Issue by AntonioCS** [HeidiSQL/HeidiSQL#1576]
**Preconditions**

* HeidiSQL version: 11.3.0.6465
* Database type and version: 
* OS: Windows10 Pro 64bit

**Describe the bug**

I opened HeidiSQL and got this:
![image](https://user-images.githubusercontent.com/1086401/165916771-5b32728a-55cd-4c91-92b2-bcdd4fc35e8e.png)
Normally I am able to click the button to download but it seems to be disabled.
The only thing I can do is click on "View changelog" and "Skip"

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
This is probably not clear enough, the build downloads are disabled when your major version is behind the last installer. You have to use the upper link "Download version x" before you can continue to download the nightly builds:

![grafik](https://user-images.githubusercontent.com/7986591/166095174-861d470c-c9f4-4ec3-b809-a435eed85121.png)

This is intentionally, so you get new and updated files from the installer which you otherwise not have.

**Comment by AntonioCS** [comment]
Oh right, got it. Completely missed the link there, thanks for pointing it out.
Please do make it a bit more obvious, thanks!
