### ISSUE TITLE
Copying table from database to another cause crash (MariaDB)

### ISSUE THREAD

**Issue by FingerlessGlov3s** [HeidiSQL/HeidiSQL#1597]
**Preconditions**

* HeidiSQL version: 12.0.0.6507
* Database type and version: MariaDB 10.7.4
* OS: Windows 10

**Describe the bug**

I'm connected to the MariaDB server and I have full rights on all databases. When I right click copy a table and copy it to another database with the same table name, it'll copy over the table and data if ticked, then Heidi SQL crashes, when the job is finished

**To Reproduce**
1. Open a server connection with at least 2 databases
2. In database 1 find a table that isn't in database 2
3. Right the source table, "Create New" -> "Table copy"
4. Change database destination to database 2
5. Press OK

**Screenshots or Crash reports**

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/8797806/bugreport.txt)

**Comment by ansgarbecker** [comment]
Related: e5486ebc5e57f35bcca88870a155e19c9d483ae7 and this old ticket: https://sourceforge.net/p/heidisql/tickets/3250/
Worth to mention you need to have a background color set in your session, and the target database must be expanded in the tree to reproduce the crash.
Should be fixed in the next build.

**Comment by FingerlessGlov3s** [comment]
Thank you for fixing, this has been annoying for me the last few months. 😀
