### ISSUE TITLE
After inserting row, unable to add timestamp entry in column field.

### ISSUE THREAD

**Issue by rayjharvey** [HeidiSQL/HeidiSQL#1645]
HeidiSQL: 12.1.0.6538 running on Windows 11
MariaDB: 10.6.9
Table Column in question Datatype: TIMESTAMP
Table Column in question Default (non-custom): current_timestamp() ON UPDATE current_timestamp()
Other columns in table Datatype: TINYTEXT

I can insert a row. I can insert text into the other columns. However, when I click on the TIMESTAMP column it populates the field as expected and when I click out I get the error. I then cancel editing and attempt to delete the row and receive an additional error.

I have included screenshots of the two errors:
![Screenshot 2022-08-17 093128](https://user-images.githubusercontent.com/97087438/185149513-4b9e7a79-3fe5-46f1-a522-fa9276486db7.png)
![Screenshot 2022-08-17 093214](https://user-images.githubusercontent.com/97087438/185149544-b534e945-1976-4d4b-9f0f-3a8e8aad00bf.png)

If it is something I am doing, or not doing, I apologize.

**Comment by ansgarbecker** [comment]
To reproduce the issue:
* create table:
```sql
CREATE TABLE `issue_1645` (
	`camera` TINYTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`object` TINYTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`time_seen` TIMESTAMP NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
);
```
* insert a row with values in the first two fields, leave the third column empty. Post the insert.
* Note the time_seen value is an empty string, not NULL.
* modify the time_seen value by editing it, post the update, causing an SQL error: `Truncated incorrect datetime value: ''`

I just pushed a fix, which uses NULL as the initial value for columns with an expression. That way, the UPDATE uses a NULL value instead of the empty string.

But that does not help if the column already has a timestamp value assigned by the server. **You still need to refresh the grid once after inserting a row without a timestamp value**.
