### ISSUE TITLE
Changing column from LONGTEXT to JSON doesn't work through UI

### ISSUE THREAD

**Issue by frankkaaijk** [HeidiSQL/HeidiSQL#1652]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: MySql 5.7.39-1.el7
* OS: Windows 10

**Describe the bug**

See: https://stackoverflow.com/questions/73470402/convert-mysql-longtext-column-to-json

**To Reproduce**

See https://stackoverflow.com/questions/73470402/convert-mysql-longtext-column-to-json

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Can you please retry with the latest build, or at least with the latest release (12.1)

**Comment by frankkaaijk** [comment]
I've tried the scenario as described in the link with version 12.1.0.6537. 

The result is the same: SQL Error (1253): COLLATION 'utf8mb4_bin' is not valid for CHARACTER SET 'binary'

Using a SQL statement gives the desired result (column is converted to JSON)

**Comment by ansgarbecker** [comment]
Ok, the issue is that the server rejects the modification when you keep the collation. The error message from the server is quite clear, you just have to remove the collation:
![grafik](https://user-images.githubusercontent.com/7986591/193878050-d9b477be-074b-4926-9d37-fb71e8b32c80.png)

It seems that MySQL 5.7 silently sets the character set of a JSON column to `binary`, which makes the previously used collation `utf8mb4_bin` incompatible.
Next build does no longer add a collation clause to any JSON column.
