### ISSUE TITLE
view: formatting of query reset to one line string

### ISSUE THREAD

**Issue by penCsharpener** [HeidiSQL/HeidiSQL#166]
## Steps to reproduce this issue

1. write a query long enough when creating a view
2. save view
3. click on another table or item in the left pane and again that newly created view

## Current behavior

HeidiSQL doesn't really format nicely the query in the view 'manager'. Maybe it is related to my version of MySQL but it always writes it into in line. I have to use VS Code with a plugin to put the query back into a readable format. 
In my sandbox with MariaDB it works meaning the query formatting is saved the way I left it.

also a database, table and column names are automatically wrapped in back ticks and `*` is resolved to all columns (which would be a nice optional feature). 

block comments are removed entirely (`/*blablabla*/`)

## Expected behavior

save the view query formatting

## Possible solution

a) if it's a server problem Heidi could at least check whether the query is only one line long and apply its own formatting. 
b) I have to upgrade that MySQL server hoping that this will fix it.

## Environment

* **HeidiSQL version:** 
HeidiSQL 9.5.0.5253 64bit
* **Database system and version:** 
MySQL 5.7.16
MariaDB 10.2.12

**Comment by ansgarbecker** [comment]
This is a server-side issue. MySQL and MariaDB are reformatting the view code when you store it.

Due to that, HeidiSQL attempts to load the original view code with such an adventurous SQL command:
```sql
SELECT CAST(LOAD_FILE(CONCAT(IFNULL(@@GLOBAL.datadir, CONCAT(@@GLOBAL.basedir, 'data/')), 'mydb/myview.frm'))
AS CHAR CHARACTER SET utf8);
```
... plus parsing the contents of the "source=" section.

This works in many cases, but not in all, and in also not in yours (obviously). For such cases, the only way to make it readable again is to use HeidiSQL's reformatter (<kbd>Ctrl+F8</kbd>). While this reformatter is quite dumb and not configurable, it should not be fired automatically.

This issue should be reported to the server's ticket systems. Most likely there are several other reporters already complaining about them, so you should find something on Google.

**Comment by danitxo** [comment]
It happens to me on a Debian 8 with MySQL 5.5.53. I have the original SQLs saved on .sql files.

It was reported years ago, but it was rejected (I think) because the type assigned was wrong ("MySQL WorkBench" instead of "MySQL"). Here is the [URL](https://bugs.mysql.com/bug.php?id=62308).
