### ISSUE TITLE
Remove multiple databases

### ISSUE THREAD

**Issue by jeromep01** [HeidiSQL/HeidiSQL#1660]
I needed to remove many databases from my host, and when i copied the 'DROP DATABASE ...' in the SQL request ta, only the first line was executed.

I then removed them one by one, but every time i do this, the SHOW DATABASE run. Could you add an option to disable the SHOW DATABASE in order to avoid hanging ?

And could you allow many requests to be executed, unless i've missed something ?

**Comment by ansgarbecker** [comment]
In the query editor, you can of course fire multiple queries at once. Just hit F9 or press the "play button". The queries have to be terminated with a semicolon. You probably used the "Run current query" menu item, or...?

To speed up the datbase content lookup, you could uncheck the option "Get full table status" in the Advanced tab of the session:
![grafik](https://user-images.githubusercontent.com/7986591/190852092-16d31c7d-32bb-47c3-a5dc-66b6715f5691.png)
I cannot fully disable the content lookup, because the tables in it are used to generate a warning to the user, so he sees what he's about to delete in such a case.
