### ISSUE TITLE
TIMESTAMP

### ISSUE THREAD

**Issue by nander80** [HeidiSQL/HeidiSQL#1666]
Hi CURRENT_TIMESTAMP on update is missing under the default column when Datatype TIMESTAMP is set? I have the latest night build version 12.1.0.6546

**Comment by ansgarbecker** [comment]
Indeed, these were missing in the functions-mariadb.ini and functions-mysql.ini, most likely due to a bug in my PHP script which should have generate and parse these functions from the MySQL help tables.
Fixed in the next installer build. Note you either need to use the installer, or just download the both updated ini files and place them in your HeidiSQL program directory:
* https://github.com/HeidiSQL/HeidiSQL/blob/master/out/functions-mariadb.ini
* https://github.com/HeidiSQL/HeidiSQL/blob/master/out/functions-mysql.ini
