### ISSUE TITLE
Missing quotes in 'SHOW OPEN TABLES FROM'

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#173]
## Steps to reproduce this issue

Open Heidi, in eventlog the line number +/- 10 starts with "SHOW OPEN TABLES FROM " after we have the database name, there are missing quotes for MySQL '`' or other databases.

## Current behavior
SHOW OPEN TABLES FROM databasename WHERE in_use!=0;

## Expected behavior
SHOW OPEN TABLES FROM \`databasename\` WHERE \`in_use\`!=0;

## Possible solution
Put missing quotes in database name and in in_use variable (just to format)

* **HeidiSQL version:** 9.5.0.5256 (64 Bit)

**Comment by ansgarbecker** [comment]
"in_use" is now always quoted, although it's not a reserved keyword.

The database name is only quoted when required - e.g. when it has spaces. This is done to avoid clutter in the log panel:
```sql
SHOW OPEN TABLES FROM `with space` WHERE `in_use`!=0;
SHOW OPEN TABLES FROM test WHERE `in_use`!=0;
```

**Comment by rentalhost** [comment]
I think better you reconsider using quote forcefully for any table name once that it could not be on your `MySQLKeywords` (_and you will broke HeidiSQL how I did now_).

**Eg. MariaDB reserved keywords than not is for MySQL:**

* BIGINT
* BINARY
* BLOB
* CHAR
* CURRENT_DATE
* CURRENT_TIME
* CURRENT_TIMESTAMP
* CURRENT_USER
* DECIMAL
* DOUBLE
* FLOAT
* GENERAL
* IF
* IN
* INT
* INTERVAL
* LEFT
* LOCALTIME
* LOCALTIMESTAMP
* LONGBLOB
* LONGTEXT
* MEDIUMBLOB
* MEDIUMINT
* MEDIUMTEXT
* RECURSIVE
* REPEAT
* RIGHT
* SLOW
* SMALLINT
* TINYBLOB
* TINYINT
* TINYTEXT
* UTC_DATE
* UTC_TIME
* UTC_TIMESTAMP
* VARBINARY
* VARCHAR
* WINDOW

PS.: Sorry because of this long list. haha

**Comment by lukinhaspm** [comment]
@ansgarbecker sorry but I'm don't understand why cluter in show open tables and no in next line 'USE'? Its ok for me, but only to understand...
eg. 
SHOW OPEN TABLES FROM lucas_teste WHERE \`in_use\`!=0;
USE \`lucas_teste\`;
