### ISSUE TITLE
Sign unsigned dll files within the app folder

### ISSUE THREAD

**Issue by hj-collab** [HeidiSQL/HeidiSQL#1733]
Hi @ansgarbecker,

There are many unsigned dll files within the app folder. Can they be signed? Unsigned files cannot run under WDAC hardened environment. May be you can sign them with your digital signature? Thanks!

If that is not possible then please can the MS Store app be updated to the latest version? It's easy to whitelist an MS Store app in WDAC. Will be happy to pay for the MS Store App. WinSCP, another FOSS app have free version on their site and a paid version on MS Store app.

**Comment by ansgarbecker** [comment]
I suppose you mean the 3rd party libraries, or?
I don't think I should sign libraries from someone else with my own signature...

**Comment by ansgarbecker** [comment]
The MS Store version of HeidiSQL is dead, due to the discontinued Desktop App Converter. I'm not willing to hassle with the newer but worse MSIX Packaging tool.

I just gave it a try with the unsigned libmysql.dll, signed it with my own certificate without problems.

I'm still a bit concerned about my certificate, after reading [this comment on SO](https://stackoverflow.com/a/13124096).

Could you please list the files which WDAC complains about. I just see libmariadb.dll already has a signature, as well as some others.

**Comment by ansgarbecker** [comment]
Thanks for the listing. I signed these (in both 32 and 64 bit versions) so the latest nightly installer has them. Please install the [32+64bit installer](https://www.heidisql.com/installers/HeidiSQL_12.3.0.6604_Setup.exe) to see if WDAC does not complain any longer.

**Comment by ansgarbecker** [comment]
The uninstaller in the new installers are now signed with my personal certificate. You can test again using the installer build 6605 from the [nightly builds page](https://www.heidisql.com/download.php#nightlybuilds).

That UAC thing is a different thing, that should go in a different ticket. I think that's currently not possible with InnoSetup, at least not to offer both paths.
