### ISSUE TITLE
Is there any linux version for this ?

### ISSUE THREAD

**Issue by Pream-webapps** [HeidiSQL/HeidiSQL#1754]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
No, HeidiSQL is available for Windows only. Due to the used VCL components it is impossible to compile it for Linux. A Linux version would require to rewrite the whole application.
You might try to run HeidiSQL through Wine - many users seem to do that successfully, although I heard from various incompatibilities.
