### ISSUE TITLE
SingleLineMode property errors

### ISSUE THREAD

**Issue by uschuster** [HeidiSQL/HeidiSQL#1774]
**Preconditions**

* HeidiSQL version: not relevant
* Database type and version: not relevant
* OS: not relevant

Commit SHA: 0fedb314ebd0f749b0ab8a8ec09052df2562f73b (March 1, 2023)

**Describe the bug**

I have used HeidiSQL for the EMBT QP report https://quality.embarcadero.com/browse/RSP-40747 and there is a mismatch between the components and main.pas.

**To Reproduce**

Setup project and IDE from scratch and open main.pas:
- clone repo (I have used Commit SHA: 0fedb314ebd0f749b0ab8a8ec09052df2562f73b (March 1, 2023) )
- run build-res.bat in the root dir of the HeidiSQL working copy
- start the IDE (11.3 in my case)
- open working copy\packages\Delphi11.2\heidisql.groupproj
- install VirtualTreesD.dpl from the project group
- install SynEdit_D.dpl from the project group
- activate project heidisql.exe
- open main.pas

Expected: no issues
Actual: SingleLineMode property errors

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
`SingleLineMode` is a property which was added to the SynEdit sources provided in components/synedit. See https://github.com/HeidiSQL/HeidiSQL/blob/f4a41cd45da54b00cf3c819070cf0eb9c21c10e9/components/synedit/Source/SynEdit.pas#L1075C7-L1075C7 . It is if I recall right the only addition I made compared to the official SynEdit repository. So your error is probably caused by using the official SynEdit parallely to the one used by HeidiSQL?
