### ISSUE TITLE
On startup, HeidiSQL tries to access non-existing directories

### ISSUE THREAD

**Issue by gwselke** [HeidiSQL/HeidiSQL#179]
## Steps to reproduce this issue

1. I start HeidiSQL (double-click on icon)
2. Then I get a modal dialog saying (translated from German): 
There is no disk in the drive. Put a disk into drive \Device\Harddisk1\DR4
Abort/Retry/Ignore
3. I then hit either Retry or Ignore. In any case, the same dialog will be shown 8 more times.
4. Then finally HeidiSQL starts.

## Current behavior
The modal dialog described above is shown in total 9 times, only then HeidiSQL starts.

## Expected behavior
HeidiSQL starts without modal dialogs with warnings.

## Possible solution
Several previous versions showed the dialog once only, then HeidiSQL would start.
It seems that the problem comes up only when certain drive mappings (maybe H: ?) exist, but do not have a directory DR4 on it.
A possible cause might be debug code accidentally left in the source. If the drive in question does not exist at all, Heidi will start without problems. But if it exists (and does not have DR4 on it), it will complain.

Possible solution: 
Remove debug code.

## Environment
Cf. "Possible solution" above.

* **HeidiSQL version:** 
9.5.0.5261
  
* **Operating system:** 
Windows 7

**Comment by ansgarbecker** [comment]
In the HeidiSQL sources, there is nothing referencing some "DR4" folder. So that must be something different. Probably a dll which is loaded implicitly by the Delphi libraries. Or your user documents reside on that folder?

Could you please downgrade HeidiSQL to the official v9.5 release (r5196), and report back if the problem persists? As I have no clue how that happens it is probably required to test more nightly builds, to narrow down the change where the problem was introduced.

**Comment by gwselke** [comment]
Thank you for the ultra-fast reply, Ansgar!
I'll do the downgrade. (wasn't even aware of not using an official release ;-)
\Gisbert


Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 5. März 2018 7:02:12 nachm. schrieb Ansgar Becker 
<notifications@github.com>:

**Comment by ansgarbecker** [comment]
Closing due to no feedback.
