### ISSUE TITLE
Suggestions for UIimprovement

### ISSUE THREAD

**Issue by erchbox** [HeidiSQL/HeidiSQL#185]
## Current behavior

Annoying behavior in the tree pane
It is really annoying that after deleting or refreshing a database branch (e.g. Tables)  the status is not maintain and the whole branch gets collapsed.

Run/Run Selection
There is no need to have two different keystrokes. The run command could run by default the selected statements or the entire query if no selection is made. This would eliminate the chance of running the whole query by mistake despite having some code selected.

## Possible solution

I would suggest to emulate the MySQL Workbench's behavior

* **HeidiSQL version:** 
  9.5.0.5261
* **Database system and version:** 
  mariaDB 10.2.13

**Comment by ansgarbecker** [comment]
Please don't report multiple topics in one issue. Make separate issues instead.

The refresh issue was already reported - see #16 .

For the run/run selection issue - that's how it is in HeidiSQL. That's not wrong, probably just not like in MySQL Workbench, but well documented in HeidiSQL and many users are used to that since several years. Using one keystroke for two different things can be confusing, so I highly disagree here.

**Comment by erchbox** [comment]
I did not wrote that something was wrong but just made a suggestions based on my personal experience using HeidiSQL and the many times that despite having selected some statements I press the wrong key  and launch the entire query.

As I see it, we are talking about doing only one action: Running SQL code and a single smart keystroke could handle it perfectly by just checking the selection status and running just the selected statements or entire query as appropriate. Nothing confusing about that.

In real life, there are plenty of dual state actions (power On/Off, Start/Stop engine, etc) that are usually handled with a single switch.

Of course, HeidiSQL is your product and it is up to you to decide how it works. As a user I can only make suggestions.
