### ISSUE TITLE
Function editor disregards DELIMITER quirk

### ISSUE THREAD

**Issue by UrsusArctos** [HeidiSQL/HeidiSQL#1866]
**Preconditions**

* HeidiSQL version: 12.5.0.6741
* Database type and version: MySQL 8.0.32
* OS: Gentoo Linux (server-side), Windows (client-side)

**Describe the bug**

Builtin function editor does not respect DELIMITER quirk described [in the official MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/stored-programs-defining.html).
Which leads to MySQL syntax error for a functions with multiple statements wrapped in BEGIN-END block.
Strangely though it does not affect stored procedures, only functions.

**To Reproduce**

1. Right-click on the DB, choose Create New => Stored Function.
2. Give function a name and a return type.
3. Write something multiline in the "Routine body" such as
```
BEGIN 
 RETURN 2;
END
```
4. Press Save button
5. See error message: 
SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'END' at line 21

The CREATE query for the function, generated by HeidiSQL, should looks like this
```
CREATE FUNCTION `test`()
RETURNS INT
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN 
 RETURN 2;
END
```
This query fails. According to the link above the problem is that multiline bodies may contain semicolon symbol which somehow breaks the entire CREATE FUNCTION statement by early terminating it (????). So the solution they suggest is to use DELIMITER statement to temporarily change delimiter to something non-semicolon. Like that:
```
DELIMITER $$
CREATE FUNCTION `test`()
RETURNS INT
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN 
 RETURN 2;
END $$
DELIMITER ;
```
This query works.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Scratching my head, because there should not be such an error as long as you use HeidiSQL's function editor. Note that when you create a function in a query tab, you need the `DELIMITER xyz` command. But in the function/procedure editor, HeidiSQL is aware of the compound statements, and executes the whole `CREATE` code in one query, so there is no need to use the `DELIMITER xyz` client command.
I just tried to reproduce but I can't:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/b7fa0328-eea6-4e8b-9b04-562ad4ad7f30)

**Comment by UrsusArctos** [comment]
Hmm. I swear it had produced an error yesterday under the same conditions.
But I can't reproduce it now either.
Will be watching, thanks for the feedback.
