### ISSUE TITLE
Improve collations support for MariaDB 10.10+

### ISSUE THREAD

**Issue by gabrielrbarbosa** [HeidiSQL/HeidiSQL#1917]
Some more collations were added and structural changes were done in MariaDB 10.10 as per https://jira.mariadb.org/browse/MDEV-27009 which requires changes in how we get the full list of collations if we are using this engine.

**Comment by ansgarbecker** [comment]
This is not a valid request. Please provide some details about what you would like to have changed in HeidiSQL.

**Comment by gabrielrbarbosa** [comment]
Does heidiSql provide utf8mb4_uc1400_ai_ci collation for example? I coundt find it

**Comment by ansgarbecker** [comment]
HeidiSQL provides all collations the server returns from `SHOW COLLATION`. Other collations not returned by that query are not supported.

**Comment by TonyGravagno** [comment]
Necro-comment ... I just loaded a new MariaDB today, v11.5.2. They still have an older version of HeidiSQL bundled with that - the one that only has the "uca1400_ai_ci" names and not the full collation name. This was confusing because right under the collation selection box it says the default is 'utf8mb4_uca1400_ai_ci', and yet that option is not available.

So I came to this project, and saw that an update might help.  
I installed HeidiSQL under the MariaDB install location, rather than as a separate app :   
C:\Program Files (x86)\Common Files\MariaDBShared\HeidiSQL  
Now with HeidiSQL v12.8 I do see utf8mb4_uca1400_ai_ci, and the world is just a little better than before. ;)

The point of this comment: The current HeidiSQL supports the current default MariaDB full collation name, but the version bundled with MariaDB doesn't have this version, and this could complicate new installs, updates, and migrations.  
I know @ansgarbecker has no control over other projects, but a nudge to the MariaDB folks to update their bundled package could save some people some grief.
