### ISSUE TITLE
Server info tooltip being persistently visible

### ISSUE THREAD

**Issue by routinet** [HeidiSQL/HeidiSQL#1929]
**Preconditions**

* HeidiSQL version: 12.5.0.6677
* Database type and version: MariaDB 10.4.25
* OS: Win10 Pro 21H2

**Describe the bug**

The status bar has a mouse-over area for the current server.  When the mouse hovers on that area, a tooltip appears with information about the connection.  In some cases, this tooltip remains persistently visible after moving the mouse out of the area, or even focusing on other apps.  It appears over every other window, obscuring vision until it decides to disappear. 

This happens most often when the mouse-over is a transient event, such as when the mouse transits over the hot area without stopping.

**To Reproduce**

**Screenshots or Crash reports**

Screenshot of the tooltip displaying properly, with the mouse-over area highlighted:
![image](https://github.com/HeidiSQL/HeidiSQL/assets/5899388/5cec4645-5d19-4c6d-90e6-ea03f3701705)

Screenshot of the tooltip displaying intrusively over another application (this issue report in a browser):
![image](https://github.com/HeidiSQL/HeidiSQL/assets/5899388/2e537fb2-460b-4b59-a0e8-792fc6187021)

**Comment by routinet** [comment]
Commenting to add that maximizing/restoring the HeidiSQL window does not impact how often this occurs.  This can also occur regardless of connection status.

**Comment by ansgarbecker** [comment]
Never saw that persistence yet. I am trying with a very fast mouse-move, and switching to another app by <kbd>Alt+Tab</kbd>, but the balloon is always hiding immediately.

Sidenotes:
* the balloon hint also hides automatically after 10 seconds
* apart from that, the balloon only gets explicitely hidden when the mouse leaves the status bar. That could probably be tricked with a high-sensitivity mouse setting, or something other special setting which causes that [StatusBarMouseLeave](https://github.com/HeidiSQL/HeidiSQL/blob/59c2122113a18923c1cafddfd170282f4ed89324/source/main.pas#L1548) event not to be triggered.

Please update to the latest release first, and then to the latest build, to verify the issue is still there.

**Comment by ansgarbecker** [comment]
Thanks for reporting back. So there remains an issue, which I cannot reproduce here.
I just looked into the code, and I cannot see how it happens. So I guess it's just a rare case with remote sessions or virtual machines.

**Comment by routinet** [comment]
I am also unable to reproduce the issue with VPN+RDP.  Whatever it was, it is gone now.  :)
