### ISSUE TITLE
update libmariadb.dll and plugin libraries to latest version

### ISSUE THREAD

**Issue by rusher** [HeidiSQL/HeidiSQL#1946]
**Is your feature request related to a problem? Please describe.**
Current shipped MariaDB library is 3.2.6. Since then, there has been lots of correction/improvement. I think specifically about https://jira.mariadb.org/browse/CONC-686, that was truncating SSL error message. 
like : 
![error_when_connect](https://github.com/HeidiSQL/HeidiSQL/assets/618074/2c84e57b-6229-490a-84b4-e99a041425e3)

in place of error like "ERROR 2026 (HY000): TLS/SSL error: Server certificate validation failed. The signature of the certificate cannot be verified. Error 0x8"

**Describe the solution you'd like**
Update library tp recent version [3.3.8](https://mariadb.com/kb/en/mariadb-connector-c-3-3-8-release-notes/)

I would have done a PR for that, but you probably want to ensure doing that yourself, wanting to ensure dll provenance...

**Comment by ansgarbecker** [comment]
Thanks for the hint. Indeed that (most important) library has not received much attention [for two years now](https://github.com/HeidiSQL/HeidiSQL/commits/master/out/libmariadb64.dll). I will check dependencies and test the current version myself.

**Comment by ansgarbecker** [comment]
Working in the latest nightly installer.

**Comment by vaintroub** [comment]
unfortunqately it is slightly backwards in the bug report. 

the message boxin the picture has the correct, non-truncated message. [CONC-686](https://jira.mariadb.org/browse/CONC-686) was not there in the older version, and it is fixed first in 3.3.10, rather than 3.3.8 by this commit https://github.com/mariadb-corporation/mariadb-connector-c/commit/83951feec94e77be5986403682d5030d7869204b


Perhaps it is not critical, but I'd switch to 3.3.10 as soon as it is available.

**Comment by ansgarbecker** [comment]
Thanks for the hint @vaintroub . I'll keep an eye on the connector releases.

**Comment by ansgarbecker** [comment]
Updated libmariadb.dll to v3.3.10
