### ISSUE TITLE
About enhanced SQL editing with VIM plugin

### ISSUE THREAD

**Issue by MrGuoCN** [HeidiSQL/HeidiSQL#1958]
**Is your feature request related to a problem? Please describe.**
Excuse me. While editing SQL in the Query tab, I find the default editor sometimes cumbersome. I would like to be able to write SQL using VIM operations within HeidiSQL. I think this would enhance user editing efficiency and comfort.

**Describe the solution you'd like**
I suggest adding a lightweight VIM plugin to HeidiSQL, which users can enable or disable via a button located under Tools -> Preferences -> SQL.

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
> I find the default editor sometimes cumbersome

You should really write more details about what is cumbersome.
My impression is you're just used to VIM, and are not willing to get used to other editors.
HeidiSQL has its own approach for SQL editing, which includes syntax highlighting, keyboard shortcuts, completion proposal, dark/light mode etc.
Additionally, there is no plugin API in HeidiSQL, so that would be the first feature you request.

Please be more precise with your request. I can probably modify a few features to what you like to have, but only if that makes sense for a majority.

**Comment by MrGuoCN** [comment]
> > I find the default editor sometimes cumbersome
> 
> You should really write more details about what is cumbersome. My impression is you're just used to VIM, and are not willing to get used to other editors. HeidiSQL has its own approach for SQL editing, which includes syntax highlighting, keyboard shortcuts, completion proposal, dark/light mode etc. Additionally, there is no plugin API in HeidiSQL, so that would be the first feature you request.
> 
> Please be more precise with your request. I can probably modify a few features to what you like to have, but only if that makes sense for a majority.

Sorry, Maybe..., You're right.I might indeed be just used to the keyboard shortcuts of VIM and not willing to get used to other editors, It seems that the one who needs to make changes is me, not HeidiSQL.By the way, this is my first Issue, and I apologize if there was anything inappropriate in my Comment.

**Comment by ansgarbecker** [comment]
No need to be sorry. There are just very many issue reports. So it's always good to be as precise as possible.

**Comment by manhthang2504** [comment]
I would love to have a VIM movement in HeidiSQL.
Currently, Heidi is great because it's fast (lightweight) and easily export to Excel. But it will bring our productivity to the next level if it have VIM movement. It will be as pleasure as Sublime (Text editor) and Obsidian (Note taking app) for a SQL Client.
