### ISSUE TITLE
UI display is shrinking on table tabs: Options

### ISSUE THREAD

**Issue by Stephanus44** [HeidiSQL/HeidiSQL#1959]
**Preconditions**

* HeidiSQL version: 12.7.0.6850
* Database type and version: MySQL 15.1 Distrib 10.4.25-MariaDB & MySQL 8.0.36
* OS: Windows 11 Build 22631 & Ubuntu 20.04.1

**Describe the bug**

The UI display is crashing on table tabs: Options. supposed its in full display to the empty side.

**To Reproduce**

1. Go click to any table, click 'Options' tabs. (In here the UI don't have problems)
2. Go click to any trigger.(No need to do anything)
3. Go click to any other table, click 'Options' tabs. (In here the UI seems shrinking in Encode, Engine, union side)

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/168423534/12382331-1d73-438d-9a98-55980e5837a5)

**Comment by ansgarbecker** [comment]
Should be fixed in the next build. I could only set the right dimensions via code, as I could not find the real cause for it.
But I found out the shrinking is only done when the editor tab is active, and then clicking a table in the tree, away from a trigger or view or something else. If the click on a table involves a tab switch from the database tab to the editor tab, no shrinking was done. However, the new fix should be sufficient I guess.
