### ISSUE TITLE
Exporting views, generates incorrect SQL DROP statement.

### ISSUE THREAD

**Issue by caiola** [HeidiSQL/HeidiSQL#20]
See example bellow, it should be DROP VIEW IF EXISTS:

DROP TABLE IF EXISTS `view_test`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_test` AS select 123 as abc;

**Comment by ansgarbecker** [comment]
Views have to be created as tables first in an SQL export, then, when all tables have been created, the "view-table" has to be dropped and the real view is created. This is all due to dependencies between views and tables. When a view references a not yet exported table, you would get a "table xyz does not exist" when creating the view earlier as the referenced table. So, there is a DROP TABLE found, but there should also be a DROP VIEW, isn't it?

**Comment by caiola** [comment]
I actually do not agree because it might give inconsistencies when restoring a .sql backup.
For example, I was just changing the definer of the view and was testing the restore and it was saying that the view already exists and could not be created.

Drop the view and run this SQL twice, to see what I mean.

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `view_test`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_test` AS select 123 AS `abc`;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

**Comment by ansgarbecker** [comment]
Using the current version of HeidiSQL, I get a different export with a `CREATE TABLE` first (conditional comments stripped):
```
CREATE TABLE `view_test` (
	`abc` INT(3) NOT NULL
) ENGINE=MyISAM;

DROP TABLE IF EXISTS `view_test`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_test` AS select 123 AS `abc` ;
```

Settings were: don't drop tables, but create tables (all default):
![export-view](https://user-images.githubusercontent.com/7986591/33514673-4d8e2ba8-d758-11e7-9407-92d547f0c2b1.png)

**Comment by caiola** [comment]
That's the issue, I don't have any TABLE `view_test` :)

Which makes the instruction DROP TABLE IF EXISTS `view_test`; a nonsense :)

**Comment by ansgarbecker** [comment]
HeidiSQL first creates a table with the same name as the view, then, after everything was exported, it drops that table and creates the real view. This is important, because a view can have a dependency on a later created table, or even a later created view!

Also note, that between the `CREATE TABLE` and `DROP TABLE`/`CREATE VIEW`, there are several other exports, e.g. a table which is used by the later created view.
