### ISSUE TITLE
Creating new INT columns becomes INT(10) instead of INT(11)

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#2017]
### What where you trying to do?
Create a new column of type INT.

### What actually happened?
A column type of INT(10) was created.

### What did you expect to happen?
I expected MySQL default INT(11).

### HeidiSQL version

12.8.0.6925

### Database server version

-

### Reproduction recipe

Create a new column of type INT, but leave the length omitted.

**Comment by ansgarbecker** [comment]
The server silently sets the integer display width. I think 10 is set when your column is marked as `signed`, and 11 for `unsigned`. It's nothing you should worry about, as it has nearly no effect on anything. The [docs](https://dev.mysql.com/doc/refman/8.4/en/numeric-type-attributes.html) say:

> This optional display width may be used by applications to display integer values having a width less than the width specified for the column by left-padding them with spaces.

Also note that integer display width is deprecated since MySQL 8.0.17. HeidiSQL does not show the display width on newer MySQL versions, since #1088.

**Comment by ansgarbecker** [comment]
Thanks for your feedback.
Probably in phpMyAdmin you were looking at a MySQL 8.x server?
