### ISSUE TITLE
Text editor: fail to show \0 characters

### ISSUE THREAD

**Issue by rentalhost** [HeidiSQL/HeidiSQL#202]
## Steps to reproduce this issue

Simplified test case that will acts exactly if you could open in the text editor:

1. Step 1; run `SELECT "test\0test";`
2. Step 2; try copy the result row that displays "test test".

## Current behavior

It will strip text until the first `\0` chacater.

## Expected behavior

Copy/show full text.

## Environment

* **HeidiSQL version:** 5263 (last)

**Comment by rentalhost** [comment]
More specific example:

```
CREATE TABLE `null_test` ( `text` TEXT NULL );
INSERT INTO `null_test` (`text`) VALUES ("test\0test");
SELECT `text` FROM `null_test`;
```

Do a double click on result grid, and you will see that `text\0text` will be replaced by just `text`.

**Comment by ansgarbecker** [comment]
In Sep 2013, I removed two functions which could probably work around these cut strings when they contain null characters, see a38c70b99ef29857a16903eb5d956dfc9307131f 
I removed these because at that time the detection of text encoding was broken, but nowadays that could be all not a problem any more. But however, that code just removed null characters, so that would be a workaround, not a solution, even it would break the text. The edit controls in HeidiSQL just do not support null characters, so I am unsure what is better - removing null characters intentionally, or let it be broken "by design" :)

**Comment by rvanlaak** [comment]
Have you by any chance been able to dive into supporting `NUL` characters?

https://stackoverflow.com/questions/3684677/remove-null-characters-from-widestring-in-delphi-2006
http://www.delphipages.com/forum/showthread.php?t=103657

**Comment by ansgarbecker** [comment]
Just a bit. As said before, I am unsure whether to just remove NUL chars, like your first web link shows it. That is perhaps better than displaying cut off text.

**Comment by rob-baker-ar** [comment]
I'm having this issue when trying to display the content of BLOB fields (which in fact contain serialized PHP objects)

Perhaps a configuration option to switch between removing NUL chars or cutting the text off?

**Comment by baukezwaan** [comment]
Maybe it's an idea to make the field readonly? And give a warning if you want to edit it?

We're also experiencing issues with serialized PHP object in a text-field. Now it is easy to misinterpret the data, when there is something missing at the end of the line. When the inline-field is not editable, and fully visible via the 'Text editor' pop-up. There you would have more interface elements to explain why it is read-only - and confirm if you really want to edit the field manually since the NUL-characters will be lost.

**Comment by ansgarbecker** [comment]
In the next build:
* text editor now auto-replaces NUL characters with a space, and activates read-only mode in such cases
* copying values does the same
