### ISSUE TITLE
Option to change the color of highlight fields with same value

### ISSUE THREAD

**Issue by albertdick** [HeidiSQL/HeidiSQL#224]
I'd like to suggest that the new "highlight fields with same value" feature of #71 might have an option to change the default color. Default color is light grey, as well as NULL field and the selected line. So, "to many shades of grey".

**Comment by ansgarbecker** [comment]
Just done. Please update to the latest build and report back if that works for you as expected.

**Comment by albertdick** [comment]
It's working as I expected.
Thank you!

**Comment by yphastos** [comment]
There's a minor bug with this feature.

Steps:
- Have a result set / data, with few rows/columns,
- click on any cell with same data as some others in same column. All cells with same data get highlighted with the same color (expected behavior)
- now click **outside** the table, (but inside the result section). The previously clicked cell loses focus, but also loses the highlight color, (the rest of 'same value' cells do keep the common color).
- The expected result would be that the cell that lost focus, should have the same color as the rest of the cells, so visually they are all the same.

Should I open this as a new issue?

**Comment by yphastos** [comment]
Update. 
When clicking outside the table, the previously selected cell doesn't lose focus, because it keeps the dotted border, and pressing the arrow keys in the keyboard change the selected cells, coloring other cells if applicable.

But it does lose color when clicking outside the table (and inside same section). And now i notice that it also removes the highlight from the selected ROW, but not from the same value cells.

I think it should either remove both highlights (row and same value cells), or keep both.

Note that clicking in other areas of the UI (the query section, the tables list, other tabs, the log area, etc) doesn't remove the highlights (row, cell, and same value cells) but does remove focus (as expected).
