### ISSUE TITLE
Wrong ID after insert row in postgres database (problem with serial)

### ISSUE THREAD

**Issue by RadekH1** [HeidiSQL/HeidiSQL#279]
## Steps to reproduce this issue

1. create table with serial primary key 
for example:
CREATE TABLE test
(
  id serial NOT NULL,
  test integer,
 PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
2. insert row via editor (autoincrement field is nextval...)
3. do insert 5 times
4. after insert is id not incremented by 1 (step is more one than 1)
![obrazek](https://user-images.githubusercontent.com/39887474/40891555-cf483570-6787-11e8-9985-482f28cecaf2.png)

## Current behavior

id is not incement by 1

## Expected behavior

id must be increment by 1

## Possible solution

in version 9.5.0.5196 is behavior OK

## Environment

problem is in great heidisql application

* **HeidiSQL version:** 9.5.0.5278
  
* **Database system and version:** postgres 9.4 but it is not depend on version postre database
  
* **Operating system:** windows

**Comment by arturm11** [comment]
After inserting each row SELECT...WHERE id=nextval() is called. I believe it should be replaced with should be curval().

**Comment by arturm11** [comment]
Problem occurs also in version 10.0.6005 :-(

![Przechwytywanie](https://user-images.githubusercontent.com/8614317/84517389-8bb00d80-accf-11ea-819f-567883cf8e45.PNG)

**Comment by ansgarbecker** [comment]
Sorry for the long delay.

@arturm11 How should the SELECT look like instead? I just tested with `.. WHERE "id"=curval('user_id_seq'::REGCLASS)` like you suggested, but that returns an SQL error.

**Comment by eramart** [comment]
There is a typo here - should be `currval`

**Comment by arturm11** [comment]
Sorry, my mistake, function name is **currval**. According to documentation:
`nextval(regclass) | bigint | Advance sequence and return new value`
`currval(regclass) | bigint | Return value most recently obtained with nextval  for specified sequence`
https://www.postgresql.org/docs/current/functions-sequence.html
I am not sure where exactly bug is, anyway it looks that you call nextval multiple times while it should be called only once per each inserted row.

**Comment by mavar74** [comment]
Maybe this could also help:
_**insert into table (col2, col3) VALUES ('c1','c2') returning id;**_

id is column where sequence is set as a default value...

https://dba.stackexchange.com/questions/3281/how-do-i-use-currval-in-postgresql-to-get-the-last-inserted-id/3284

**Comment by arturm11** [comment]
Hello again. I tried to install Delphi IDE and pull source code from git to do some debugging but this is too much for me. Borland's Turbo Pascal on MSDOS is what I remember :-)
Anyway, please look into "dbconnection.pas" file. Procedure "TDBQuery.SaveModifications". You test columns against cdtAutoInc feature. If found, you call "SELECT LAST_INSERT_ID()" and assign result to column and clear "NewIsNull". Active connection is PG, so there is no autonumber and NewIsNull is left to true.
Then you refresh row using key columns. For above test table key column is a function "nextval('test_id_seq'::regclass)" (converted from "serial" pseudotype). Thus, whole sequence after you click update button is:

<pre><code>
INSERT INTO "public"."test" ("test") VALUES ('1');
SELECT "id", "test" FROM "public"."test" WHERE  "id"=nextval('test_id_seq'::regclass);
</code></pre>

While for MySql it looks like:

<pre><code>
INSERT INTO `sakila`.`actor` (`first_name`, `last_name`) VALUES ('test', 'test');
SELECT LAST_INSERT_ID();
SELECT `actor_id`, `first_name`, `last_name`, `last_update` FROM `sakila`.`actor` WHERE  `actor_id`=201;
</code></pre>

I can see 2 solutions:

1. PostreSQL substitute for "SELECT LAST_INSERT_ID()" is "SELECT lastval()". Problem is that there is no AUTO_INCREMENT keyword in PG. Wrong results can also occur when RULE and DO ALSO on another table is used but this is rare case.

2. Replace word "nextval" by "currval" in function on selecting row.

Solution given by mavar74 is almost OK, but this is of course wrong to assume that autonumber column is named "id".

**Comment by tanzanite777** [comment]
Oww. Got hit by this MAJOR bug today (thankfully, on non-live server) - and found, to may dismay, that the bug has been known and ignored for YEARS!

I do not see any assignment nor priority tags - is this bug forgotten? If any dev sees this - please give a life-sign as an much appreciated sanity check.

Having not seen the code - the correct way to do (in postgres) what i see in Heidi log window: "INSERT ..." followed by "SELECT ... last_insert" - is to combine the two.

"INSERT INTO ... VALUES (...) RETURNING *;"

This will return the added row(s) after defaults (including sequences) and triggers have done their job.

Read more at: https://www.postgresql.org/docs/current/dml-returning.html

**Comment by ansgarbecker** [comment]
Sorry for the delay. I will have a look at that. Only I need an additional query, like the `SELECT LAST_INSERT_ID()` for MySQL. So, is `SELECT lastval()` correct?

**Comment by tanzanite777** [comment]
Glad to see active ticket monitoring :D. Was worried for a bit.

For convenience on lastval / currval: https://www.postgresql.org/docs/current/functions-sequence.html

'lastval()' returns connection specific last sequence invocation result (ie. last application of 'nextval') - which in this context would be technically invalid as HeidiSQL is a generic tool that does not know targeted database specifics and cannot make the needed assumptions for proper usage of 'lastval':
* last insert could have invoked multiple sequences directly (sequences are a generic tool and can be used for other purposes besides single PK generation)
* last insert could have caused other inserts and/or sequence invocations indirectly (through triggers / rules)

'currval(seq-name)' could alleviate it slightly by requesting for specific sequence - but still fails if there is a trigger / rule that does something (ex: insert or whatever else) affecting the same sequence.

I do not know whether this behavior has changed recently, but i highly doubt it given that far superior generic RETURNING was added for postgres version 11+ removing the need to know how the row gets formed. I know that MySQL LAST_INSERT_ID was also unusable in similar context for similar reasons back then - but has had developments since 5.something that made it a bit more reliable (have not used MySQL for a long time, but have seen mentioned that it still has some relevant gotchas - whether true or not i do not know).

So, technically - the only correct way is RETURNING.

However, i have noticed that there is some form of separation in Heidi for resulting INSERT and relevant SELECT when adding new rows - indicating that fixing that might be difficult (as your question also seems to indicate).

As a quick half-fix you could use 'lastval' as it will work in the wast majority of cases and does not break much if it fails (returning some random irrelevant value) - but, more importantly, won't wreck the sequence!
