### ISSUE TITLE
Heidi not on top

### ISSUE THREAD

**Issue by mets11rap** [HeidiSQL/HeidiSQL#333]
When you open Heidi, it's not a top program. This means it's overlapped by things such as Rainmeter.

**Comment by ansgarbecker** [comment]
You probably mean HeidiSQL is not _always_ on top, which is very normal behaviour.

**Comment by penCsharpener** [comment]
@ansgarbecker  I think @mets11rap  means something else. 
When I have HeidiSQL running and then in the taskbar hold Shift and click the icon to start a new instance it doesn't open on top (more behind the previous instance). I have to first click on the taskbar icon to pop up all the opened instance and then select the new one to bring it to front. That is annoying indeed. 
I don't think anyone wants HeidiSQL to be always on top. 

My expectation is that when I open a new instance it opens in the foreground so that I can immediately use it.

**Comment by ansgarbecker** [comment]
I just expect issue reporters to fill out the issue template. So there is no need to speculate about what he meant.

But yes, thanks for the explanation :)

**Comment by penCsharpener** [comment]
should I create a new issue?

**Comment by mets11rap** [comment]
Example:
![image](https://user-images.githubusercontent.com/20345400/44460848-a8e88900-a5dc-11e8-8cb2-1afd24ce1106.png)
@ansgarbecker
