### ISSUE TITLE
SQL Dump exponentially slows down depending on the number of records in a table

### ISSUE THREAD

**Issue by neszt** [HeidiSQL/HeidiSQL#343]
## Steps to reproduce this issue
Right-click on a (large) table and select "Export database AS SQL" option;

- Table(s): Create
- Data: Insert
- Max INSERT size: 4096 (we tested several different sizes including 0, but it is always too slow)
- Output: Directroy - one file per object in database subdirectories

## Current behavior

- Table size 0 - 10.000 records: about 5000 record / sec
- Table size 10.000 - 100.000 records: about 1000 record / sec
- Table size 100.000 - 200.000 records: about 500 record / sec
- Table size 200.000 - 300.000 records: about 200 record / sec

## Expected behavior

Dump time should slow down linearly.

## Possible solution

We see high CPU usage, so it's not a disk related problem. Probably this is an algorithmic bug in HeideSQL's code, we beleive it can be fixed.

## Environment

* **HeidiSQL version:** 
HeidiSQL version: 9.5.0.5293 (most recent at 2018-09-02 16:52:56)
* **Database system and version:** 
Database system and version: MSSQL
* **Operating system:** 
Operating system: Windows 10

**Comment by ansgarbecker** [comment]
I suppose this performance slowdown is related to Microsoft SQL mode, or proably the queries are working here, probably due to the lack of an offset in `SELECT` queries.

**Comment by neszt** [comment]
Well, this was our first guess, but we double checked in the MSSQL query log: only one query executed, "SELECT * FROM table LIMIT 1000000" or something like that. Accordingly, there is no significant disk load, just 100% CPU, and when multiple tables are dumped simultaneously, it is more faster as more CPU core can work paralell.

**Comment by ansgarbecker** [comment]
Slow processing seems to be caused by large result processing with the underlying ADO/dbGo library.

Reason for large results was I didn't have a plan for iterating through large MS SQL tables with some limit/offset clause - I just knew of the `TOP(..)` clause. Today I learned about the `OFFSET/FETCH` clause of the `ORDER BY` clause on https://www.sqlservertutorial.net/sql-server-basics/sql-server-offset-fetch/ . At least on SQL Server 2012 upwards this is supported.

So, HeidiSQL now retrieves larges tables in chunks of ~10,000 rows. Exporting a table with 300,000 rows took 25 seconds now, and there is no exponential slow down any longer.

Please test yourself and watch out for SQL errors due to the changed syntax.
