### ISSUE TITLE
Stored Procedure CREATE Code Error

### ISSUE THREAD

**Issue by leach35** [HeidiSQL/HeidiSQL#391]
## Steps to reproduce this issue
![mariadberror](https://user-images.githubusercontent.com/25161950/48319663-7ac48500-e5de-11e8-9658-00b7e13a0116.png)

Create any stored procedure or function. For instance, I created a stored procedure that gets all users on a particular team. Once the procedure is how I would like it to be, I save it and test it to make sure it works correctly. Once I know it works correctly I copy the "CREATE Code" tab from the procedure to have it generate it from my local to my remote server. This fails every time with the following error dialog that says:
"SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 18".

How can this be wrong when this code is generated?

## Current behavior
Fails to create the stored procedure and/or function

## Expected behavior

the stored procedure and/or function should be created.

## Possible solution

I have no idea.

* **HeidiSQL version:** 
HeidiSQL 9.5.0.5332
* **Database system and version:** 
 MariaDB 10.3.10
* **Operating system:** 
Windows 10 Professional

**Comment by ansgarbecker** [comment]
The SQL code is most likely not working due to contained delimiters, which is by default semicolon (;). The routine editor internall ignores these command delimiters, while the query editor uses these to detect the end of a command. If you change the delimiter to something else before firing the SQL in a query tab, for example to "//", it will probably run fine.

Please check if that's the case and report back if that did not work.

**Comment by ansgarbecker** [comment]
Note: changing the delimiter can be done by clicking the button on the main toolbar, with the red semicolon on it.
