### ISSUE TITLE
sql loading error

### ISSUE THREAD

**Issue by narthkain** [HeidiSQL/HeidiSQL#567]
## Steps to reproduce this issue

1. Step 1;
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2949542/bugreport.txt)

2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by narthkain** [comment]
Importing SQL files larger than 5MB results in errors

**Comment by ansgarbecker** [comment]
This is most probably a translation error, due to a missing or duplicated placeholder in the language you have selected. Your crash report says that was Korean, and I found the issue in the Korean translation for
> Selected files have a size of %s

... was translated as
> 선택된 파일은 %a 크기를 가짐

Now my Korean is a bit ... rusty :) But I think I could fix the translation - changed the %a to %s . Now we just have to wait for some Git source modification which triggers the build process.

**Comment by ansgarbecker** [comment]
Should be fixed in the meantime. If not please shout.
