### ISSUE TITLE
Widow does behaves weird when external monitor connected.

### ISSUE THREAD

**Issue by kamalsofteng** [HeidiSQL/HeidiSQL#633]
## Steps to reproduce this issue

1. Step 1 have multiple monitors attached to your computer(I have 2 plus the laptop );
2. Step 2 Just open the program;
4. Then see the window spread all over the three monitors. It is extremely frustrating as you have to size the window to fit it on one screen every time you open it.

## Current behavior

windows (main and connection manager) windows don't have sizing capability.

## Possible solution

I think setting the correct view port takes care of window being on all monitors. Making the window sizable is likely to fix the issue where the winnow controls are out of view. Setting parent to child windows is also likely to fix the issue where each window is on a separate screen without any apparent connection, say you can't click on the parent window when connection manage is open.

## Environment

Windows 10, two monitors attached to laptop. I don't remember having this issue just two weeks ago when I was on windows 7.

![h-sql3](https://user-images.githubusercontent.com/2684232/57033949-44c29e00-6c1c-11e9-92ab-baf0635250de.PNG)
![h-sql1](https://user-images.githubusercontent.com/2684232/57033950-44c29e00-6c1c-11e9-9dce-c2691ab0579d.PNG)
![h-sql2](https://user-images.githubusercontent.com/2684232/57033951-44c29e00-6c1c-11e9-8fca-3e4c221972de.PNG)

* **Operating system:** 
Windows 10

**Comment by itpimp** [comment]
Same. Especially when using field selection or predictive columns.

**Comment by ansgarbecker** [comment]
Please update to the latest build. I dropped high-dpi awareness recently, and this obviously describes an issue with high dpi settings. I planned to support it and worked several months on that, but could not manage all the new bugs, so I dropped it - with the latest build you should see a correctly zoomed windows with slightly blurry text.

**Comment by itpimp** [comment]
Tx. Did update. Problem persists on both field selection and field prediction popup on secondary screens.

**Comment by ansgarbecker** [comment]
Really? Even if you once decrease the window to normal sizes?

**Comment by itpimp** [comment]
![image](https://user-images.githubusercontent.com/9435040/66718740-76ed4400-ede7-11e9-8597-66e000fb71e4.png)

My config: primary left, secondary center, tertiary right. I'm working on tertiary. What I have noticed, if I right click on a column, it shows the column selection perfectly under the mouse/column I've clicked. But if I click "Columns", it starts the column selection screen on my primary screen and extend all the way to my tertiary screen.

If I'm working on primary or secondary, things get worse, as the column selection goes all the way past primary screen's left most bounds.
If heidi is not maximized, it'll

**Comment by ansgarbecker** [comment]
Which build number are you using?

**Comment by itpimp** [comment]
10.2.0.5713

**Comment by itpimp** [comment]
![image](https://user-images.githubusercontent.com/9435040/66719858-444a4800-edf5-11e9-952a-04acf0464298.png)

**Comment by itpimp** [comment]
I'm downloading 5716 now and testing.

**Comment by itpimp** [comment]
Same effect.

**Comment by ansgarbecker** [comment]
Ok, then do you have some non-100% DPI setting on one or more of your screens?
Did you already try to reduce the window size?
I am currently loosing the overview here - I am not sure if you mean what you reported at the top of this report?

**Comment by itpimp** [comment]
My setup is a bit different, though. I have a laptop with dual graphics cards and 3 screens. All my display settings on all screens are set to recommended in display settings. All 100% sizes.

I think the original poster and I share the same issue. The windows appear over multiple screens and have to be moved to get access to the window sizing or content of the window.

What I've done:
I've unplugged my tertiary monitor and only using primary and secondary. I've placed the app on the secondary monitor. If I select "Columns" button, the columns popup's left most side displays on the primary screen, like this.
![image](https://user-images.githubusercontent.com/9435040/66720742-17039700-ee01-11e9-9330-4ba0de68ca84.png)
At the bottom of the image you can see my taskbar, complete with notification icon area. Then you see the start menu button again (which I have enabled to displayed on my secondary screen as well) and my taskbar on the secondary monitor. 

It's as if the popup uses the primary screen to determine display position, rather than the current screen the app is rendered on display to do calculations.

**Comment by itpimp** [comment]
Additionally, my screens do have different resolutions and do not all run through the same GPU.

**Comment by itpimp** [comment]
"Restore defaults" did the trick! Lost settings, but small price to pay for such a huge gain.

![image](https://user-images.githubusercontent.com/9435040/66930376-c5dbe900-f034-11e9-9367-310c8883a101.png)

**Comment by itpimp** [comment]
Thanks guys

**Comment by ansgarbecker** [comment]
Didn't you before resize the window via mouse? That should have done the same, without losing all your other settings.
