### ISSUE TITLE
Is it possible to change the "Class" of process?

### ISSUE THREAD

**Issue by darklonely** [HeidiSQL/HeidiSQL#743]
hello, recently i tried the "HoeKey". It's a great tool.
right now, HeidiSQL's "Class" is "TMainForm", it's same with launcher Executor.  
when i config the `show | TMainForm`, the Executor showed, instead of HeidiSQL.

**Comment by ansgarbecker** [comment]
Hm, I don't think I want to change that class name. Also because I have no clue how to name it other than main form. What if you ask the developer of that launcher Executor?
And why does that "HoeKey" software not even look at the application's name? The class name of different applications windows can of course be ambiguous.

**Comment by darklonely** [comment]
ok. i will try to ask the developer of Executor.
i agree with you. The class name method is ambiguous and inconvenient. 
thanks for your answer.
