### ISSUE TITLE
donate button

### ISSUE THREAD

**Issue by plakhin** [HeidiSQL/HeidiSQL#746]
## Steps to reproduce this issue

1. Step 1; Open about window. Enter email use who made donation, click "ok".
2. Step 2; Close about window. Big green "Donate" button disappeared.
3. Step 3; Close HeidiSql. Open again. Donate button is back.

## Current behavior

Donate button is back on each restart.

## Expected behavior

Donate button not appearing after on restart after entering email of user who made donation.

## Environment

Windows 10

* **HeidiSQL version:** 
  10.2.0.5684, first issue appeared in 5683

**Comment by ansgarbecker** [comment]
Can confirm that. Maybe a logic problem in the changed code.

**Comment by ansgarbecker** [comment]
I got feedback from an external user that the last build solves the issue. Could you please verify?

For me the log panel also shows now this, probably different to what you get:
![grafik](https://user-images.githubusercontent.com/7986591/64904220-11624680-d6c7-11e9-8ff8-55d1739e4e54.png)

**Comment by plakhin** [comment]
Checked build 5685, still getting donate button after restart. I can check again tonight and provide more details if you tell me what details you need.

**Comment by plakhin** [comment]
Just updated to 5687 and still getting donate button after restart.
Also I noticed `/* Access is denied */` message in console right after starting HeidiSQL and opening a connection.

**Comment by ansgarbecker** [comment]
Please post what you get in the log panel in that "Check success response:" line. Please use the latest build (currently 5687).

**Comment by Cubittus** [comment]
For me the problem is a bit different, so this might be an unrelated issue.  The donate button used to be hidden since I donated a few years back.  The button reappeared recently and now I can't remove it.

With Build 5688 when I press the OK button in About I immediately get 'Could not check donation state'.
The log panel shows (after many attempts):

/* Check success response: "漱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "蜱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "팱" */
/* Check success response: "餱" */
/* Check success response: "퀱" */
/* Check success response: "由" */
/* Check success response: "팱" */
/* Check success response: "週" */
/* Check success response: "팱" */
/* Check success response: "팱" */

I ran Wireshark to check whether there was a network issue and I can see that a https encrypted request is made to the ip address of the heidisql.com domain, and an encrypted response is received.

If I use this browser on the same machine to visit
https://www.heidisql.com/hasdonated.php?email=<my paypal email address>
then I get a page showing '1', which, according to the source, suggests that I have not donated, which is wrong.  I still have the email from you acknowleding the donation, sent to that email address.

**Comment by ansgarbecker** [comment]
"1" means yes, "0" means no.

The problem is that broken character, which I cannot detect as "1", obviously. As you reported the issue was introduce with the change in build 5683. Relevant code is this, but I still don't know why that fails on some systems, and not on mine here:

    var
    Buffer: array[1..4096] of Byte;
    BytesInChunk: Cardinal;
    ContentChunk, FLastContent: String;
    ...
    FLastContent := '';
    ...
    SetString(ContentChunk, PChar(@Buffer[1]), BytesInChunk);
    FLastContent := FLastContent + ContentChunk;

**Comment by plakhin** [comment]
Build 5688. Absolutely the same behavior.  
After starting HeidiSQL, I get `/* Access is denied */` and donate button.
After opening "About" window I get `/* Check success response: "̱" */`
After entering email: `/* Check success response: "1" */` and button gets hidden.
But after restarting everything is the same again.

**Comment by plakhin** [comment]
When making curl requests to the `https://www.heidisql.com/hasdonated.php?email=` with my email address inserted, I'm always getting `1` as a response and not that broken characters.

**Comment by plakhin** [comment]
Just checked build 5682, it behaves correct. So confirming that issue appeared since 5683.

**Comment by Cubittus** [comment]
A couple of revisions to my comment above (github munged it somewhat):

Re: the missing email - The email check I did in my browser did use my email address - github lost it when I submitted the comment.

Re: 1 for yes - I was looking in the source code at main.pas line 12843 in the HasDonated function.  The comments there lead me to think that 0 meant not checked, 1 meant not a donor and 2 meant valid donor, but reading further I see that the variable FHasDonatedDatabaseCheck is a simple boolean.

**Comment by ansgarbecker** [comment]
@Cubittus : the comments refer to `FHasDonatedDatabaseCheck` which is my weird `TThreeStateBoolean` type, defined as `(nbUnset, nbFalse, nbTrue)` - 0/1/2 internally. The http result is different - just "0" or "1".

However, I just changed the buffer data type from Byte to AnsiString, and now it's starting at 0 instead of 1st character. Please update again and see what that "Check success" says now.
And sorry for the mess..

**Comment by Cubittus** [comment]
I just tried again with build 5689 - same result:
```
/* Check success response: "ေ" */
/* Check success response: "팱" */
/* Check success response: "팱" */
```
That is what the log shows after trying the OK button twice.  The first line with the UTF 0x1031 is from the startup check for the toolbar button (I am assuming).

The 0x1031 caught my eye as 0x31 is the ascii codepoint for '1'.  Could there be some issue involving internal conversion between windows 'unicode' (UTF-16) and UTF-8 or ASCII string types, or with the result string not being terminated correctly.
What makes it more interesting is that the other strange character 팱 is Unicode 0xD331.  Again the low byte is 0x31 == '1'.
I'm not too familiar with Pascal, but I have fought similar problems when writing C++ code.

Thanks for looking into this!

**Comment by ansgarbecker** [comment]
Thanks, that hex code was a good hint. Asked on Stackoverflow for the right decoding approach: https://stackoverflow.com/q/57951463/4110077
And I think I got it now. Please test once more with the latest build.

**Comment by Cubittus** [comment]
Build 5690 works perfectly for me - the Donate button is now hidden upon startup, and pressing OK in the About dialog gives the 'Thanks for donating!' message.

Thanks for a great application and top-notch support!

**Comment by plakhin** [comment]
Build 5691 works perfect. Thanks everyone.
