### ISSUE TITLE
I hope can open and edit multiple tables at the same time

### ISSUE THREAD

**Issue by GitHubAdminis** [HeidiSQL/HeidiSQL#748]
## Steps to reproduce this issue

1. Step 1;
open table
2. Step 2;
open another table
3.  the first table is closed;;

## Current behavior

After editing the first table, open the second table, the first table will be closed

## Expected behavior
Can open and edit multiple tables at the same time

## Environment

* **HeidiSQL version: 10.2.0.5685** 
  
* Database system and version: MySQL 
  
* **Operating system: Windows 10 1903 18362.356**

**Comment by ansgarbecker** [comment]
You probably did not think your idea to the end: if you click table A, then B, then A again, should there be 2 or three tabs? Also, you ignored the Data tab - once we have multiple table tabs, we also need multiple Data tabs.

The current single-designer/data tab is intentional and is an important idea of mine. There must be really good reasons to give that up, so here's quite a few feedback required.

**Comment by ansgarbecker** [comment]
Closing due to no feedback

**Comment by mtaki14** [comment]
>The current single-designer/data tab is intentional and is an important idea of mine

@ansgarbecker Can you please elaborate on this a bit more? Since you say it is intentional, how is the current single designer/data tab workflow advantagous to having a set of chosen table views open for easy access? Maybe the optimal way way of doing things is one I haven't considered, but I always found the lack of tabs in heidisql something that is holding it back while otherwise being an extremely complete program.

**Comment by eflames** [comment]
The fact that the system was initially thought to have a single tab does not mean that it is the best solution. The other editors have the tabs to their advantage. Why if it is clearly an advantage, you don't want to add it?

**Comment by Germs2004** [comment]
> Closing due to no feedback

I would also like this feature. Here's a use case:
When I am editing the schema of TableB, sometimes I want to refer to TableA's schema. I need to go back and forth several times to copy or verify column names or datatypes from TableA to TableB. Without this feature, if I make one change to TableB and try to go look at TableA again, it asks if I want to save my changes to TableB or lose them. But, I'm not ready to save changes yet because there are additional things I still need to copy from TableA.

I promise no offense is meant here, but I come from Microsoft SQL Server, and SSMS allows us to have many table schema ("Design") tabs at once.  They stay until we choose to close them.

A workaround is to open two instances of HeidiSQL.

> You probably did not think your idea to the end: if you click table A, then B, then A again, should there be 2 or three tabs?

Perhaps the Data tabs could be moved to the table's sub-tab (the row with Basic, Options, Indexes, etc).  That way, they stay organized with each Table.  I personally might prefer that anyway.  Clicking a table with a tab already open could just makes that table's tab the active one, and the Table tabs don't close unless we click their X.
![image](https://github.com/HeidiSQL/HeidiSQL/assets/5519340/be7c1eec-6f86-4718-9444-655a2baeeb64)

Just my opinion.  Thank you for your consideration.

**Comment by heham** [comment]
I think maybe dbeaver's tabs is good.

**Comment by EKIKOUKA** [comment]
> I think maybe dbeaver's tabs is good.

I'm currently using DBeave, and DataGrip is better than DBeave, but DataGrip is expensive.
