### ISSUE TITLE
MySQL 8.0 - Export views problem

### ISSUE THREAD

**Issue by cammudito** [HeidiSQL/HeidiSQL#752]
## Steps to reproduce this issue

Hi, there's a problem exporting a database to another one. Using Mysql 8.0 and Heidi 10.2.0

1. Select database to export: "Export dababase as SQL"
2. Select Table: Drop and Create
3. Select Data: Delete + insert (truncate existing data)
4. Select output: Dabase
5. Click Export
6. On view's I get error "SQL Error 1347: xxxx is not VIEW "

## Current behavior

Views get error when exporting "SQL Error 1347: xxxx is not VIEW "
They have been created as tables.

## Expected behavior

Views have not been exported as "Views"

## Environment

* **HeidiSQL version:**  10.2.0.5695
  
* **Database system and version:**  Mysql Version: 8.0.17 - Database Collation: utf8mb4_0900_ai_ci
  
* **Operating system:** Windows 10 
  

Image 1
![Screenshot_2](https://user-images.githubusercontent.com/932077/65414731-8d117100-ddf4-11e9-99a0-aa54feec5b18.png)
Image 2
![Screenshot_3](https://user-images.githubusercontent.com/932077/65414735-900c6180-ddf4-11e9-9b42-afadbc744d8b.png)
Image 3
![Screenshot_4](https://user-images.githubusercontent.com/932077/65414739-91d62500-ddf4-11e9-8fd7-6c11be41d2db.png)

**Comment by ansgarbecker** [comment]
Problem is in MySQL 8, the changed behaviour of `DROP VIEW xyz`. The new behaviour is described here: https://dev.mysql.com/doc/refman/8.0/en/drop-view.html
Though the docs say clearly when using `DROP VIEW IF EXISTS xyz`, then just a note returns, not an error. HeidiSQL fires the query due to the checked left checkbox (Drop tables), and fires it with the `IF EXISTS` clause, which should avoid the error. Obviously, it still returns with an error if `xyz` exists as a table. I am unsure if that's a bug in MySQL or if that's intentionally. The docs are incomplete however, and I have no idea for a workaround.

**Comment by GGG-KILLER** [comment]
I believe the root of this issue is not the `DROP VIEW IF EXISTS xyz`, but that HeidiSQL is creating the views as tables when moving things from one DB to another.

I attempted to do this on a **totally empty** DB and HeidiSQL created the views as tables which in turn caused this issue.

**Comment by GGG-KILLER** [comment]
A possible solution would be to do the same thing mysqldump does to solve this:

```sql
--
-- Temporary view structure for view `xyz`
--

DROP TABLE IF EXISTS `xyz`;
/*!50001 DROP VIEW IF EXISTS `xyz`*/;
SET @saved_cs_client     = @@character_set_client;
/*!50503 SET character_set_client = utf8mb4 */;
/*!50001 CREATE VIEW `xyz` AS SELECT 
 1 AS `x`,
 1 AS `y`,
 1 AS `z`*/;
SET character_set_client = @saved_cs_client;

-- Rest of the dump...

--
-- Final view structure for view `xyz`
--

/*!50001 DROP VIEW IF EXISTS `xyz`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8 */;
/*!50001 SET character_set_results     = utf8 */;
/*!50001 SET collation_connection      = utf8_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`john.doe`@`%` SQL SECURITY DEFINER */
/*!50001 VIEW `xyz` AS SELECT actual_contents FROM the_view */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;
```

**Comment by rabrego** [comment]
You can check this example of exported file 
[Heidi DB TESTDB.txt](https://github.com/HeidiSQL/HeidiSQL/files/9398449/Heidi.DB.TESTDB.txt)

### **1. There is a command to drop the VIEW**
-- Dumping structure for view testdb.v_table1
DROP VIEW IF EXISTS `v_table1`;

### **2. Another command create the view as TABLE**
-- Creating temporary table to overcome VIEW dependency errors
CREATE TABLE `v_table1` (
	`identificador` INT(10) NOT NULL,
	`valor` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci'
) ENGINE=MyISAM;

### **3. VIEW is tried to be dropped again, here the error is raided because the object is a TABLE**
-- Dumping structure for view testdb.v_table1
DROP VIEW IF EXISTS `v_table1`;

### **4. TABLE is dropped and the VIEW is created**
-- Removing temporary table and create final VIEW structure
DROP TABLE IF EXISTS `v_table1`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_table1` AS select `table1`.`ID` AS `identificador`,`table1`.`value` AS `valor` from `table1`;

I dont know if these command are generated by mySQL or by HeidiSQL

In my opinion the third point is not necessary

If you are exporting entire database you can check "Database(s) Drop" Checkbox and uncheck "Table(s) Drop" checkbox because with the first all objects are dropped

![Captura de pantalla 2022-08-22 194218](https://user-images.githubusercontent.com/22224945/186044267-16c47a1b-1c00-4606-b3f8-bf1b7b52105f.png)

**Comment by albertdick** [comment]
This issue still happens in 2023 with latest HeidiSQL v12.5.0.6751 (64-bit) on a MySQL Server v8.0.35 installed on Windows 10 Pro (64-bit).

**Comment by ansgarbecker** [comment]
Fixed in the next build.

I realized that - in case of views - dropping the original view is not required, so the code modification was simpler than I thought.

**Comment by albertdick** [comment]
The issue still happen with HeidiSQL v12.5.0.6755 (64-bit).

![image](https://github.com/HeidiSQL/HeidiSQL/assets/8559840/40edbcd6-e88b-497a-898d-e25c47cf79cb)

If you scroll down, you'll see that it export the views again with no errors. So apparently it's doing it twice?

![image](https://github.com/HeidiSQL/HeidiSQL/assets/8559840/a345c0e5-1db1-47eb-b97d-31eed881a53a)

**Comment by ansgarbecker** [comment]
Yes, there are two passes for views, that's very normal. This is done to overcome view-from-view dependencies during the export.

But are you sure you updated to the latest build? I cannot reproduce that here, anyway if I select another server or a database on the same server:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/87b7a187-ec39-4209-af36-241a5dec5777)

**Comment by albertdick** [comment]
Yes, in my case, I periodically download a database with tables, procedures, and views from the production environment to my local machine (development), and the error only occurs when the database with the views already exists.

This issue did not occur in MySQL versions 5.6 and 5.7.

**Comment by albertdick** [comment]
Ok, nevermind. I exported again the same database to my machine and the issue didn't occur anymore. I was already using the latest version of HeidiSQL v12.5.0.6755. In the meantime, I had to redo my local MySQL installation, and perhaps that was the issue.

So in fact the HeidiSQL issue has been fixed.

Thanks.

**Comment by ansgarbecker** [comment]
Thanks for your quick feedback!
