### ISSUE TITLE
Foreign keys issue

### ISSUE THREAD

**Issue by davekc** [HeidiSQL/HeidiSQL#845]
First of all, the foreign keys disappeared (not listed anymore) from the relevant tab.
Creating still them works but are not listed either.

1. Version 10.3 (from 11 Dec 2019 works as expected)
2. Build 5806 works fine too
3. Builds 5807-5809 are not

## Possible solution
Revert to a previous version

## Environment
Windows 10 x64
MariaDB 10.3.21

Thanks!

**Comment by ansgarbecker** [comment]
This is due to work in progress - I am working on a larger code enhancement, which replaces the parsing of `CREATE TABLE` code with less error prone queries. The 3 things columns, keys and foreign keys are affected here, of which the last is not yet implemented. Issue #12 gave me a hit here, as it was nearly impossible to have one procedure parsing the CREATE code of now 4 different RDBMS.

I will leave this open so we can test and verify this is all working again afterwards.

**Comment by davekc** [comment]
That was quick! Sorry, I did not mean to rush you... Glad to hear that you are aware of the situation and that you are actually working on all this. Maybe I should slow down on nightly builds updates a bit then ;) Thanks again!

**Comment by ansgarbecker** [comment]
Foreign keys should be detected again, at least in MySQL.

Todo: There was and still is no foreign key detection for MSSQL, PostgreSQL and SQLite. But this should go in other tickets, e.g. #158 and #641

**Comment by davekc** [comment]
MariaDB 10.3 works fine again, thanks a lot!
