### ISSUE TITLE
Display column comment in query result tab

### ISSUE THREAD

**Issue by AltarBeastiful** [HeidiSQL/HeidiSQL#908]
## Steps to reproduce this issue

1. Open a DB with a lot of comments on column
2. Create a complex query mixing a few table
3. Execute query

## Current behavior

Data is displayed. 
If I need to see the comment of a column to refresh my memory on it's usage, I have to go find the table and open the corresponding Table tab to see the comment explaining the column.

## Expected behavior
In the Result tab, the column comment is displayed when hovering the name. Same as the Data tab.
This would be really useful when working on large database heavily documented using comments.

Another possible solution would be to provide a way, from the Data tab to navigate to the corresponding Table tab. For example right click on a cell -> "Go to Table".

**Comment by ansgarbecker** [comment]
This is because the query itself does not provide column comments, and the relevant C API structure [`MYSQL_FIELD`](https://dev.mysql.com/doc/refman/8.0/en/c-api-data-structures.html) neither does that. For getting the comments, an additional queries had to be executed each time you run a normal query. I am against doing that, as that breaks the profiling feature, and some other things. Not sure if there's a different C API method than [`mysql_fetch_field_direct()`](https://dev.mysql.com/doc/refman/8.0/en/mysql-fetch-field-direct.html) for getting column comments?
