### ISSUE TITLE
Error reporting 

### ISSUE THREAD

**Issue by courtens** [HeidiSQL/HeidiSQL#925]
When tying to report a bug the UI is not friendly. I can not read the buttons. 
This is what I see: https://www.filmfix.com/images/UI-bug-report.jpg

## Environment

* **HeidiSQL version:**  10.3.0.5771

* **Operating system:**  Win 10 Pro

**Comment by ansgarbecker** [comment]
That component is the madExcept exception handler. I just updated that to the newest release, so the next HeidiSQL build will use it. If the problem persist, you will have to file a report on their forum: http://forum.madshi.net/
I can already tell you the issue only happens when you use a non-default style/theme. This is probably unsupported by madExcept. One way to get around that is to use the default "Windows" theme.
