### ISSUE TITLE
MySQL Double Datatype incorrect default Length/Set

### ISSUE THREAD

**Issue by FredMK** [HeidiSQL/HeidiSQL#953]
## Steps to reproduce this issue

1. Create a new table, and fill table name
2. Create a new Column and set the Datatype to Double
3. Check that the Length/Set empty
4. Save the changes
5. After the save, you will see that the Length/Set is now 22,0 (this is incorrect, because you can set value like 111.111)
6. Change the column name and save again (now the ALTER code will contain the 22,0 length/set)

## Current behavior

For DOUBLE type (didn't check other) Length/Set is incorrect for display, and will be incorrect if the column get changed via GUI)

## Expected behavior

The Length/SET must be empty if that's the current definition.

## Possible solution

Fix it.

## Environment

* **HeidiSQL version:** 11.0.0.5926
* **Database system and version:** MySQL 5.7.25

**Comment by ansgarbecker** [comment]
Please check the values of `NUMERIC_PRECISION` and `NUMERIC_SCALE` of the following query -  this is what HeidiSQL also uses to determine the length:

```
SELECT * FROM `information_schema`.`COLUMNS`
WHERE TABLE_SCHEMA='yourdb'
  AND TABLE_NAME='yourtable'
ORDER BY ORDINAL_POSITION;
```

**Comment by FredMK** [comment]
Alter code: 
```
ALTER TABLE `x`
CHANGE COLUMN `Column 1` `Column 1` DOUBLE NULL DEFAULT NULL FIRST;
````

After the information_schema:
`NUMERIC_PRECISION `: 22
`NUMERIC_SCALE`: NULL

On the GUI I see this in the Length/Set (after full DB refresh): `22,0`


Before version 11, the Length/Set was empty in this scenario.

**Comment by ansgarbecker** [comment]
Only because it's not empty any longer, this doesn't mean it's wrong now.

But I suppose that DOUBLE(22,0) is a wrong interpretation of the numeric_scale value. If numeric_scale is null, then it should probably just be DOUBLE(22). Is this correct?
Here's the relevant documentation: https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html

**Comment by FredMK** [comment]
The problem with the current behavior, that in the create code I see this:
```
CREATE TABLE `x` (
	`Column 1` DOUBLE(22,0) NULL DEFAULT NULL
)
```

The bigger problem, when I change something in the column, HeidiSQL will use DOUBLE(22,0) for type, when my current type is DOUBLE.

But this is not true, because the DOUBLE(22,0) is not the same as the DOUBLE. And the table currently not behaving as a DOUBLE(22,0), because it let me input not whole numbers like 1.1111.

**Comment by FredMK** [comment]
DOUBLE(22) is not a correct type for version MySQL 5.7, I didn't check it onMySQL 8.*.

This is not valid a syntax:
```
ALTER TABLE `x`
	CHANGE COLUMN `Column 1` `Column 1` DOUBLE(22) NULL DEFAULT NULL FIRST;
```

**Comment by ansgarbecker** [comment]
Indeed, that throws an error.

So my question is, how to interprete the 22/NULL values from information_schema.columns? HeidiSQL relies on these to get the table definition.

**Comment by FredMK** [comment]
> As of MySQL 8.0.17, the nonstandard FLOAT(M,D) and DOUBLE(M,D) syntax is deprecated and support for it will be removed in a future MySQL version.

So the ...(M,D) will be removed in the future, I won't miss it.

For DOUBLE:   
If `NUMERIC_SCALE` is null, then the Length/Set should be empty, and use syntax DOUBLE.
If not, then use the current method: DOUBLE(M,D).

For FLOAT the syntax if different:
All the syntaxes currently are valid: FLOAT, FLOAT(p), FLOAT(M,D).

The problem here, that for FLOAT(p) you cannot find the value for p in information_schema.columns. 

I cannot find a good method for FLOAT, but if you use the same method as the DOUBLE that would be a workaround.

**Comment by ansgarbecker** [comment]
Thanks for quick feedback.

**Comment by FredMK** [comment]
More information: 
10.3.0.5771 working as expected
10.3.0.5917 buggy behavior, same in version 11.

**Comment by damaltor** [comment]
I recently updated from 10.3.0.5771 to an 11 version, and nearly crashed most of our databases :)

I found out the following, using a mysql 5.7 server:
-> If you make a new table and use the DOUBLE datatype, without entering anything into the length field, the column gets correctly set up with the DOUBLE datatype.
-> afterwards, the table is shown with 22,0 in the length field, while the 22,0 is not actually in the table definition
-> if you then edit the table structure, maybe adding a column or renaming something or doing anything that ends in an ALTER TABLE command, the column gets written to DOUBLE(22,0) even if it was not touched
-> this even happens when you manually remove the errouneous 22,0 out of the length field
-> every insert from this point on will round the data inserted to zero decimals (!!). data which is already in the table is not affected
-> i did not find a way to fix affected tables in heidi. i had to resort to phpmyadmin to fix the tables. unfortunately, the data inserted while the table was affected are rounded on insert and the data does not come back. data inserted before the defect happened seems to be untouched after repairing the table.

i did now go back to 10.3.0.5771, just to be sure. it works fine there.

**Comment by ansgarbecker** [comment]
@damaltor please also update to the latest build. I already modified many things here.

**Comment by damaltor** [comment]
It is a tiny bit better now with the latest nightly build:
-> the decimal datatype still incorrectly shows up as decimal(22,0), so there is still 22,0 in the length field.
-> if you edit the table and remove the 22,0 by hand from the double columns, the datatype gets set to double and works fine
-> if you forget to remove the 22,0 from the length field, the table column still gets set to decimal(22,0) and shows the same behaviour as before

so, the table still gets corrupted by the incorrect length field if you not actively set it to "", but it is now possible to fix the table by manually removing the 22,0 from the length field without using external tools.

i will stay with the old version for now.

as a side question: After juggling with multiple versions now, the tree view in the left pane no longer works for me in any version. if i click the little plus icon in front of a db, it converts to a minus but does not expand. i have to open tables in the right pane after klicking on the db name in the tree view. is that something known, or is that something new which i should open a new report for? the issue persists even after uninstalling and reinstalling.

side side question: how can i remove heidi and all its settings (!) to do a clean reinstall? heidi seems to remember all my db info even after uninstalling.

**Comment by ansgarbecker** [comment]
@damaltor please make sure your "favorites only" button is unpressed:
![grafik](https://user-images.githubusercontent.com/7986591/82431952-a35cf300-9a8f-11ea-8db9-b5fe3ae3f5f5.png)
Please keep unrelated side questions away here, they make it hard to see read issues.

The original issue is if I understand right the superfluous default length for `DECIMAL` and `DOUBLE` data types. This is caused by my new detection of column types via IS query:

    SELECT * FROM `information_schema`.`COLUMNS` WHERE
    TABLE_SCHEMA='test' AND TABLE_NAME='whatever' ORDER BY ORDINAL_POSITION;

Also related: #1023 

I should somehow detect these default length and leave it away then.

**Comment by damaltor** [comment]
Thanks for the quick answer. The Favourites Button solved the problem nicely. That is a nice feature i did not notice so far. Great! The button looks the same when pressed and not pressed, when using the dark theme though.

Ok, back to the original question - you are right, side notes are bad in a thread.

Yes, the issue is the superfluous 22,0 in the length field. up the the latest release, it would break the table even when you removed the 22,0 out of the field when saving. in the latest nightly, it breaks the table only if you forget to clear the field manually. in both versions, the length field is shown as 22,0, no matter if the table is ok or already broken. touching the name or any other setting of the column will then change double to double(22,0) when saving.

in the old version 10.3.0.5771, as noted [here](https://github.com/HeidiSQL/HeidiSQL/issues/953#issuecomment-603745091), the field correctly shows up empty if the data type is double and the table does not get changed by accident. this is the behaviour one would like to expect. to reduce the risk of accidentially breaking production tables, i am still using that version of which i can confirm that it works perfectly.

**Comment by LexBart** [comment]
I confirm the problem.
I use 10.2.27-MariaDB.
It was very unexpected to find this problem. I usually don’t put restrictions on the double and therefore I’m used to seeing a 22,0 display in this field. But the last time this field really displayed the correct value. It took some time to determine why the values are not added. 
This is very inconvenient when double and double(22,0) are displayed the same way - 22,0

**Comment by ansgarbecker** [comment]
I suppose what @FredMK said works, so I just did exactly that:

> For DOUBLE:
> If `NUMERIC_SCALE` is null, then the Length/Set should be empty, and use syntax DOUBLE.
> If not, then use the current method: DOUBLE(M,D).

I'm not sure what older MySQL versions say. `FLOAT` columns are hopefully not broken now. Crossing fingers.

**Comment by damaltor** [comment]
Works for me. Thanks!
