### ISSUE TITLE
Feature Request - data tab - right-click update all cells with this filter

### ISSUE THREAD

**Issue by BartVanEynde** [HeidiSQL/HeidiSQL#979]
Database MariaDB
in DB > Table > Data tab you can edit a single cell
is it possible to right-click on the cell and get an 
UPDATE table SET name=_value of the cell_ WHERE _filter of data tab_

many thanks,
Bart

**Comment by ansgarbecker** [comment]
I understand the request, but why did you delete the issue template?

You will have to provide a more detailed concept in a feature request. E.g. with a graphical mockup.

**Comment by BartVanEynde** [comment]
Thank you & sorry, my first feature request
( in my mind feature requests were not issue related )

**Comment by ansgarbecker** [comment]
No problem, you're not really the first one :) Can you create some mockup which explains your idea graphically?

**Comment by ansgarbecker** [comment]
I suppose we can close this.
There is a way to achieve the same result with the search/replace dialog, which supports replacing text in a grid since some versions:

![grafik](https://user-images.githubusercontent.com/7986591/164504138-8ad29e49-6c21-4c55-a33d-6c9f4bb77da6.png)

Just shout if you have a better idea how to design such an extra `UPDATE ... WHERE...` query from within the data grid.
