### ISSUE TITLE
can't close  script tab 

### ISSUE THREAD

**Issue by gronel** [HeidiSQL/HeidiSQL#992]
## Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/4135303/79434039-6ae57780-8000-11ea-839b-820d9efcd45b.png)

## Current behavior

close menu is disable 

## Possible solution

for better user experience just add close button  like workbench

## Environment

* **HeidiSQL version: 11** 
  
* **Database system and version:** 
  
* **Operating system: Windows 10**

**Comment by ansgarbecker** [comment]
This was already said in #318 , where the discussion there went towards how to _clear_ the first tab. However, the first tab is intentionally not closable, so especially newbies cannot be confused when searching for a way to run queries.

**Comment by danitxo** [comment]
What I have seen in the image (and have been able to test) is that, if an SQL file is loaded, it does so in the first tab. Therefore, in terms of usability, at least I would add an option to "Clean tab" or similar, since nothing makes you think that with a double click you can close the opened SQL file. Or, more simply, make the SQL files load in new tabs, not in the active one.

**Comment by ansgarbecker** [comment]
More related: #365 
And for the unload feature:
* https://www.heidisql.com/forum.php?t=35851
* a343c1359f8dc154572aefef3be2b13ea1296305 (committed after the v11 release, so this will be in v11.1)

**Comment by ansgarbecker** [comment]
That "clear" feature is visible in the context menu of the editor:

![grafik](https://user-images.githubusercontent.com/7986591/79455553-5350c380-7fed-11ea-81b9-2c767ab6592d.png)
